import type { ConsoleView } from "@/components/pulse/console/layout"

export interface ViewDataRequirements {
  applications: boolean
  monitors: boolean
  runs: boolean
  alerts: boolean
  secrets: boolean
  certificateProfiles: boolean
  notificationSettings: boolean
  retentionSettings: boolean
  sloSummary: boolean
  deploymentValidations: boolean
  elfQueries: boolean
  elfProxySettings: boolean
}

const ALL: ViewDataRequirements = {
  applications: true,
  monitors: true,
  runs: true,
  alerts: true,
  secrets: true,
  certificateProfiles: true,
  notificationSettings: true,
  retentionSettings: true,
  sloSummary: true,
  deploymentValidations: true,
  elfQueries: false,
  elfProxySettings: false,
}

const byView: Partial<Record<ConsoleView, Partial<ViewDataRequirements>>> = {
  dashboard: {
    applications: true,
    monitors: true,
    runs: true,
    alerts: true,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: true,
    deploymentValidations: false,
  },
  monitors: {
    applications: false,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  applications: {
    applications: true,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: true,
    deploymentValidations: false,
  },
  "application-detail": {
    applications: true,
    monitors: true,
    runs: true,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: true,
    deploymentValidations: true,
  },
  builder: {
    applications: true,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: true,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  runs: {
    applications: false,
    monitors: true,
    runs: true,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  "run-detail": {
    applications: false,
    monitors: true,
    runs: true,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  alerts: {
    applications: false,
    monitors: true,
    runs: false,
    alerts: true,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  "alert-detail": {
    applications: false,
    monitors: true,
    runs: false,
    alerts: true,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  secrets: {
    applications: false,
    monitors: false,
    runs: false,
    alerts: false,
    secrets: true,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
  },
  settings: {
    applications: false,
    monitors: false,
    runs: false,
    alerts: false,
    secrets: true,
    certificateProfiles: true,
    notificationSettings: true,
    retentionSettings: true,
    sloSummary: false,
    deploymentValidations: false,
    elfQueries: false,
    elfProxySettings: true,
  },
  deployments: {
    applications: true,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: true,
    elfQueries: true,
    elfProxySettings: false,
  },
  "deployment-check-create": {
    applications: true,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
    elfQueries: true,
    elfProxySettings: false,
  },
  "deployment-check-edit": {
    applications: true,
    monitors: true,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: true,
    elfQueries: true,
    elfProxySettings: false,
  },
  "elf-queries": {
    applications: true,
    monitors: false,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
    elfQueries: true,
    elfProxySettings: false,
  },
  "elf-query-detail": {
    applications: true,
    monitors: false,
    runs: false,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: false,
    elfQueries: true,
    elfProxySettings: true,
  },
  "deployment-validation": {
    applications: true,
    monitors: true,
    runs: true,
    alerts: false,
    secrets: false,
    certificateProfiles: false,
    notificationSettings: false,
    retentionSettings: false,
    sloSummary: false,
    deploymentValidations: true,
    elfQueries: true,
    elfProxySettings: false,
  },
}

export function getViewDataRequirements(view: ConsoleView = "dashboard"): ViewDataRequirements {
  return {
    ...ALL,
    ...(byView[view] ?? {}),
  }
}
