// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "concepts/alerts.mdx": () => import("../content/docs/concepts/alerts.mdx?collection=docs"), "concepts/applications.mdx": () => import("../content/docs/concepts/applications.mdx?collection=docs"), "concepts/deployment-validation.mdx": () => import("../content/docs/concepts/deployment-validation.mdx?collection=docs"), "concepts/elf-log-checks.mdx": () => import("../content/docs/concepts/elf-log-checks.mdx?collection=docs"), "concepts/glossary.mdx": () => import("../content/docs/concepts/glossary.mdx?collection=docs"), "concepts/monitors-and-runs.mdx": () => import("../content/docs/concepts/monitors-and-runs.mdx?collection=docs"), "concepts/secrets-and-certificates.mdx": () => import("../content/docs/concepts/secrets-and-certificates.mdx?collection=docs"), "getting-started/navigating-the-console.mdx": () => import("../content/docs/getting-started/navigating-the-console.mdx?collection=docs"), "getting-started/what-is-rythm.mdx": () => import("../content/docs/getting-started/what-is-rythm.mdx?collection=docs"), "getting-started/your-first-monitor.mdx": () => import("../content/docs/getting-started/your-first-monitor.mdx?collection=docs"), "guides/certificate-profiles.mdx": () => import("../content/docs/guides/certificate-profiles.mdx?collection=docs"), "guides/configuring-elf-queries.mdx": () => import("../content/docs/guides/configuring-elf-queries.mdx?collection=docs"), "guides/creating-a-monitor.mdx": () => import("../content/docs/guides/creating-a-monitor.mdx?collection=docs"), "guides/importing-monitors.mdx": () => import("../content/docs/guides/importing-monitors.mdx?collection=docs"), "guides/managing-applications.mdx": () => import("../content/docs/guides/managing-applications.mdx?collection=docs"), "guides/managing-secrets.mdx": () => import("../content/docs/guides/managing-secrets.mdx?collection=docs"), "guides/notification-settings.mdx": () => import("../content/docs/guides/notification-settings.mdx?collection=docs"), "guides/running-deployment-validation.mdx": () => import("../content/docs/guides/running-deployment-validation.mdx?collection=docs"), "guides/testing-and-publishing-monitors.mdx": () => import("../content/docs/guides/testing-and-publishing-monitors.mdx?collection=docs"), "guides/viewing-runs-and-history.mdx": () => import("../content/docs/guides/viewing-runs-and-history.mdx?collection=docs"), "guides/working-with-alerts.mdx": () => import("../content/docs/guides/working-with-alerts.mdx?collection=docs"), }),
};
export default browserCollections;