import type { Monitor, MonitorRun, SecretReference } from "./pulse-types"

export const secrets: SecretReference[] = [
  {
    id: "sec-client-id",
    name: "Demo Client ID",
    alias: "clientId",
    provider: "encrypted-db",
    description: "OAuth client identifier used by the JWT prerequisite step.",
    status: "active",
    lastTestedAt: "2026-06-02T08:45:00Z",
  },
  {
    id: "sec-private-key",
    name: "Demo Private Key",
    alias: "privateKey",
    provider: "encrypted-db",
    description: "RS256 signing key. Stored encrypted and masked everywhere.",
    status: "active",
    lastTestedAt: "2026-06-02T08:45:00Z",
  },
  {
    id: "sec-slack",
    name: "Synthetic Alerts Slack Webhook",
    alias: "slackWebhook",
    provider: "encrypted-db",
    description: "Webhook for failure threshold and auto-resolve notifications.",
    status: "active",
    lastTestedAt: "2026-06-02T07:20:00Z",
  },
]

export const monitors: Monitor[] = [
  {
    id: "mon-protected-api",
    name: "Protected API Synthetic Check",
    description: "Generates JWT, fetches a token, and validates protected API health.",
    scheduleMode: "every-5m",
    scheduleLabel: "Every 5 minutes",
    cron: "*/5 * * * *",
    timezone: "Asia/Kolkata",
    timeoutMs: 30000,
    retryCount: 1,
    failureThreshold: 3,
    responseBodyLimitKb: 32,
    isActive: true,
    variables: {
      tokenUrl: "https://auth.example.com/oauth/token",
      baseUrl: "https://api.example.com",
      audience: "protected-api",
    },
    secretAliases: ["clientId", "privateKey", "slackWebhook"],
    status: "failed",
    lastRunAt: "2026-06-02T09:05:17Z",
    lastDurationMs: 1842,
    successRate24h: 96.4,
    alertPolicy: {
      enabled: true,
      threshold: 3,
      responseTimeMs: 2000,
      email: true,
      slackWebhook: true,
      cooldownMinutes: 30,
    },
    steps: [
      {
        id: "step-jwt",
        order: 1,
        name: "Generate JWT",
        type: "preRequest",
        timeoutMs: 5000,
        retryCount: 0,
        continueOnFailure: false,
        actions: [
          {
            id: "action-jwt",
            type: "generateJWT",
            label: "Generate RS256 client assertion",
            output: "jwt",
            configPreview:
              "iss/sub={{secrets.clientId}}, aud={{variables.audience}}, exp={{timestamp.epochSecondsPlus300}}",
          },
        ],
        assertions: [],
        extractors: [],
      },
      {
        id: "step-token",
        order: 2,
        name: "Get Token",
        type: "http",
        method: "POST",
        url: "{{variables.tokenUrl}}",
        timeoutMs: 15000,
        retryCount: 1,
        continueOnFailure: false,
        assertions: [
          {
            id: "assert-token-status",
            type: "statusCode",
            label: "Token endpoint returns 200",
            target: "status",
            operator: "equals",
            expected: "200",
            actual: "200",
          },
          {
            id: "assert-token-json",
            type: "jsonPath",
            label: "Access token exists",
            target: "$.access_token",
            operator: "exists",
            expected: "present",
            actual: "********",
            sensitive: true,
          },
        ],
        extractors: [
          {
            id: "extract-access-token",
            name: "accessToken",
            type: "jsonPath",
            source: "$.access_token",
            sensitive: true,
          },
        ],
      },
      {
        id: "step-health",
        order: 3,
        name: "Call Protected API",
        type: "http",
        method: "GET",
        url: "{{variables.baseUrl}}/health",
        timeoutMs: 10000,
        retryCount: 1,
        continueOnFailure: false,
        assertions: [
          {
            id: "assert-health-status",
            type: "statusCode",
            label: "Protected API returns 200",
            target: "status",
            operator: "equals",
            expected: "200",
            actual: "503",
          },
          {
            id: "assert-health-latency",
            type: "responseTime",
            label: "Responds under threshold",
            target: "latency",
            operator: "lessThan",
            expected: "2000ms",
            actual: "1842ms",
          },
        ],
        extractors: [],
      },
    ],
  },
  {
    id: "mon-public-health",
    name: "Public Health Endpoint",
    description: "Single-step GET check for the public health route.",
    scheduleMode: "every-1m",
    scheduleLabel: "Every 1 minute",
    cron: "* * * * *",
    timezone: "Asia/Kolkata",
    timeoutMs: 10000,
    retryCount: 0,
    failureThreshold: 1,
    responseBodyLimitKb: 32,
    isActive: true,
    variables: {
      baseUrl: "https://status.example.com",
    },
    secretAliases: [],
    status: "success",
    lastRunAt: "2026-06-02T09:06:02Z",
    lastDurationMs: 312,
    successRate24h: 100,
    alertPolicy: {
      enabled: true,
      threshold: 1,
      responseTimeMs: 1000,
      email: true,
      slackWebhook: false,
      cooldownMinutes: 15,
    },
    steps: [
      {
        id: "step-public-health",
        order: 1,
        name: "GET /health",
        type: "http",
        method: "GET",
        url: "{{variables.baseUrl}}/health",
        timeoutMs: 10000,
        retryCount: 0,
        continueOnFailure: false,
        assertions: [
          {
            id: "assert-public-status",
            type: "statusCode",
            label: "Status code is 2xx",
            target: "status",
            operator: "is2xx",
            expected: "2xx",
            actual: "200",
          },
        ],
        extractors: [],
      },
    ],
  },
  {
    id: "mon-partner-orders",
    name: "Partner Orders API",
    description: "HMAC-signed request flow for the partner order summary endpoint.",
    scheduleMode: "custom-cron",
    scheduleLabel: "Custom cron",
    cron: "*/10 * * * *",
    timezone: "UTC",
    timeoutMs: 20000,
    retryCount: 1,
    failureThreshold: 2,
    responseBodyLimitKb: 32,
    isActive: false,
    variables: {
      baseUrl: "https://partner.example.com",
      environment: "sandbox",
    },
    secretAliases: ["partnerApiKey", "hmacSecret"],
    status: "skipped",
    lastRunAt: "2026-06-01T18:15:21Z",
    lastDurationMs: 944,
    successRate24h: 88.9,
    alertPolicy: {
      enabled: false,
      threshold: 2,
      responseTimeMs: 3000,
      email: true,
      slackWebhook: true,
      cooldownMinutes: 30,
    },
    steps: [
      {
        id: "step-signature",
        order: 1,
        name: "Build HMAC Signature",
        type: "preRequest",
        timeoutMs: 5000,
        retryCount: 0,
        continueOnFailure: false,
        actions: [
          {
            id: "action-hmac",
            type: "hmacSha256",
            label: "Sign method, path, body, and timestamp",
            output: "signature",
            configPreview: "secret={{secrets.hmacSecret}}, payload=method:path:body:timestamp",
          },
        ],
        assertions: [],
        extractors: [],
      },
      {
        id: "step-order-summary",
        order: 2,
        name: "Fetch Order Summary",
        type: "http",
        method: "POST",
        url: "{{variables.baseUrl}}/orders/summary",
        timeoutMs: 15000,
        retryCount: 1,
        continueOnFailure: false,
        assertions: [
          {
            id: "assert-order-status",
            type: "statusCode",
            label: "Partner API returns success",
            target: "status",
            operator: "equals",
            expected: "200",
            actual: "200",
          },
        ],
        extractors: [
          {
            id: "extract-order-count",
            name: "orderCount",
            type: "jsonPath",
            source: "$.summary.total",
          },
        ],
      },
    ],
  },
]

const protectedApiMonitor = monitors[0]!
const publicHealthMonitor = monitors[1]!

export const runs: MonitorRun[] = [
  {
    id: "run-0091",
    monitorId: "mon-protected-api",
    monitorName: "Protected API Synthetic Check",
    status: "failed",
    triggeredBy: "schedule",
    startedAt: "2026-06-02T09:05:15Z",
    endedAt: "2026-06-02T09:05:17Z",
    durationMs: 1842,
    failureCategory: "HTTP_ERROR",
    failureReason: "Call Protected API returned 503 after token acquisition succeeded.",
    steps: [
      {
        id: "step-run-jwt",
        stepId: "step-jwt",
        stepName: "Generate JWT",
        type: "preRequest",
        status: "success",
        latencyMs: 24,
        requestSummary: "Generated jwt from encrypted secret aliases clientId and privateKey.",
        responseSummary: "Output jwt=********",
        assertions: [],
        extractors: [],
      },
      {
        id: "step-run-token",
        stepId: "step-token",
        stepName: "Get Token",
        type: "http",
        status: "success",
        latencyMs: 486,
        requestSummary: "POST {{variables.tokenUrl}} with client_assertion=********.",
        responseSummary: "200 application/json, body truncated to 32 KB, access_token=********.",
        assertions: protectedApiMonitor.steps[1]?.assertions ?? [],
        extractors: protectedApiMonitor.steps[1]?.extractors ?? [],
      },
      {
        id: "step-run-health",
        stepId: "step-health",
        stepName: "Call Protected API",
        type: "http",
        status: "failed",
        latencyMs: 1842,
        requestSummary:
          "GET {{variables.baseUrl}}/health with Authorization=Bearer ******** and X-Correlation-ID generated.",
        responseSummary: "503 application/json, masked and truncated to 32 KB.",
        assertions: protectedApiMonitor.steps[2]?.assertions ?? [],
        extractors: [],
        errorMessage: "Expected status 200, got 503.",
      },
    ],
  },
  {
    id: "run-0090",
    monitorId: "mon-public-health",
    monitorName: "Public Health Endpoint",
    status: "success",
    triggeredBy: "manual",
    startedAt: "2026-06-02T09:06:01Z",
    endedAt: "2026-06-02T09:06:02Z",
    durationMs: 312,
    steps: [
      {
        id: "step-run-public",
        stepId: "step-public-health",
        stepName: "GET /health",
        type: "http",
        status: "success",
        latencyMs: 312,
        requestSummary: "GET {{variables.baseUrl}}/health.",
        responseSummary: "200 application/json, body truncated to 32 KB.",
        assertions: publicHealthMonitor.steps[0]?.assertions ?? [],
        extractors: [],
      },
    ],
  },
]

export function getMonitor(id: string) {
  return monitors.find((monitor) => monitor.id === id) ?? protectedApiMonitor
}

export function getRun(id: string) {
  return runs.find((run) => run.id === id) ?? runs[0]!
}
