import type { PulseClient } from "./types"

export function createMockPulseClient(overrides: Partial<PulseClient> = {}): PulseClient {
  const notImplemented = async () => {
    throw new Error("Mock pulse client method not implemented")
  }

  return {
    listApplications: notImplemented,
    saveApplication: notImplemented,
    deleteApplication: notImplemented,
    runApplication: notImplemented,
    listApplicationServices: async () => [],
    saveApplicationService: async () => null,
    deleteApplicationService: notImplemented,
    listMonitors: async () => [],
    getMonitor: async () => null,
    updateMonitor: notImplemented,
    deleteMonitor: notImplemented,
    runMonitor: notImplemented,
    listRuns: async () => [],
    getRun: async () => null,
    listAlerts: async () => [],
    listSecrets: async () => [],
    saveSecret: notImplemented,
    testSecret: async () => true,
    deleteSecret: notImplemented,
    listCertificateProfiles: async () => [],
    saveCertificateProfile: notImplemented,
    testCertificateProfile: async () => true,
    deleteCertificateProfile: notImplemented,
    getNotificationSettings: async () => null,
    saveNotificationSettings: async () => null,
    testNotificationSettings: async () => ({ ok: true, deliveries: [] }),
    getRetentionSettings: async () => null,
    saveRetentionSettings: async (settings) => settings,
    purgeRetention: async () => ({ deleted: 0 }),
    getSLOSummary: async () => null,
    listDeploymentValidations: async () => [],
    getDeploymentValidation: async () => ({ validation: null, preRuns: [], postRuns: [] }),
    createDeploymentValidation: async () => null,
    updateDeploymentValidation: async () => null,
    deleteDeploymentValidation: notImplemented,
    runDeploymentValidationPost: notImplemented,
    runDeploymentValidationLogCheck: notImplemented,
    saveDeploymentAIReport: async () => null,
    generateDeploymentAIReport: async () => ({}),
    getElfProxySettings: async () => null,
    saveElfProxySettings: async () => null,
    testElfProxySettings: async () => ({ ok: true }),
    listElfQueries: async () => [],
    saveElfQuery: async () => null,
    deleteElfQuery: notImplemented,
    testElfQuery: async () => ({ ok: true }),
    probeElfQuery: async () => ({ ok: true, probe: { hitCount: 0 } }),
    validateElfQueryCheck: async () => ({ ok: true, criteriaResult: "pass", gateResult: "pass" }),
    ...overrides,
  }
}
