export type ConsoleView =
  | "dashboard"
  | "applications"
  | "application-detail"
  | "deployments"
  | "deployment-check-create"
  | "deployment-check-edit"
  | "monitors"
  | "builder"
  | "runs"
  | "run-detail"
  | "deployment-validation"
  | "alerts"
  | "alert-detail"
  | "secrets"
  | "elf-queries"
  | "elf-query-detail"
  | "settings"
