// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAlert = `-- name: GetActiveAlert :one
SELECT
  id,
  monitor_id,
  COALESCE(run_id, '')::text AS run_id,
  COALESCE(status, '')::text AS status,
  COALESCE(severity, '')::text AS severity,
  COALESCE(title, '')::text AS title,
  COALESCE(description, '')::text AS description,
  COALESCE(failure_category, '')::text AS failure_category,
  channels_json,
  deliveries_json,
  first_triggered_at,
  last_triggered_at,
  last_delivered_at,
  resolved_at,
  COALESCE(acknowledged_by, '')::text AS acknowledged_by,
  acknowledged_at,
  snoozed_until,
  COALESCE(suppression_reason, '')::text AS suppression_reason,
  created_at,
  updated_at
FROM alerts
WHERE monitor_id = $1
  AND status = ANY($2::text[])
ORDER BY last_triggered_at DESC
LIMIT 1
`

type GetActiveAlertParams struct {
	MonitorID pgtype.Text `json:"monitor_id"`
	Column2   []string    `json:"column_2"`
}

type GetActiveAlertRow struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	RunID             string           `json:"run_id"`
	Status            string           `json:"status"`
	Severity          string           `json:"severity"`
	Title             string           `json:"title"`
	Description       string           `json:"description"`
	FailureCategory   string           `json:"failure_category"`
	ChannelsJson      []byte           `json:"channels_json"`
	DeliveriesJson    []byte           `json:"deliveries_json"`
	FirstTriggeredAt  pgtype.Timestamp `json:"first_triggered_at"`
	LastTriggeredAt   pgtype.Timestamp `json:"last_triggered_at"`
	LastDeliveredAt   pgtype.Timestamp `json:"last_delivered_at"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	AcknowledgedBy    string           `json:"acknowledged_by"`
	AcknowledgedAt    pgtype.Timestamp `json:"acknowledged_at"`
	SnoozedUntil      pgtype.Timestamp `json:"snoozed_until"`
	SuppressionReason string           `json:"suppression_reason"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetActiveAlert(ctx context.Context, arg GetActiveAlertParams) (GetActiveAlertRow, error) {
	row := q.db.QueryRow(ctx, getActiveAlert, arg.MonitorID, arg.Column2)
	var i GetActiveAlertRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.RunID,
		&i.Status,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.FailureCategory,
		&i.ChannelsJson,
		&i.DeliveriesJson,
		&i.FirstTriggeredAt,
		&i.LastTriggeredAt,
		&i.LastDeliveredAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.SnoozedUntil,
		&i.SuppressionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlert = `-- name: GetAlert :one
SELECT
  id,
  monitor_id,
  COALESCE(run_id, '')::text AS run_id,
  COALESCE(status, '')::text AS status,
  COALESCE(severity, '')::text AS severity,
  COALESCE(title, '')::text AS title,
  COALESCE(description, '')::text AS description,
  COALESCE(failure_category, '')::text AS failure_category,
  channels_json,
  deliveries_json,
  first_triggered_at,
  last_triggered_at,
  last_delivered_at,
  resolved_at,
  COALESCE(acknowledged_by, '')::text AS acknowledged_by,
  acknowledged_at,
  snoozed_until,
  COALESCE(suppression_reason, '')::text AS suppression_reason,
  created_at,
  updated_at
FROM alerts
WHERE id = $1
`

type GetAlertRow struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	RunID             string           `json:"run_id"`
	Status            string           `json:"status"`
	Severity          string           `json:"severity"`
	Title             string           `json:"title"`
	Description       string           `json:"description"`
	FailureCategory   string           `json:"failure_category"`
	ChannelsJson      []byte           `json:"channels_json"`
	DeliveriesJson    []byte           `json:"deliveries_json"`
	FirstTriggeredAt  pgtype.Timestamp `json:"first_triggered_at"`
	LastTriggeredAt   pgtype.Timestamp `json:"last_triggered_at"`
	LastDeliveredAt   pgtype.Timestamp `json:"last_delivered_at"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	AcknowledgedBy    string           `json:"acknowledged_by"`
	AcknowledgedAt    pgtype.Timestamp `json:"acknowledged_at"`
	SnoozedUntil      pgtype.Timestamp `json:"snoozed_until"`
	SuppressionReason string           `json:"suppression_reason"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAlert(ctx context.Context, id string) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.RunID,
		&i.Status,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.FailureCategory,
		&i.ChannelsJson,
		&i.DeliveriesJson,
		&i.FirstTriggeredAt,
		&i.LastTriggeredAt,
		&i.LastDeliveredAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.SnoozedUntil,
		&i.SuppressionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT
  id,
  monitor_id,
  COALESCE(run_id, '')::text AS run_id,
  COALESCE(status, '')::text AS status,
  COALESCE(severity, '')::text AS severity,
  COALESCE(title, '')::text AS title,
  COALESCE(description, '')::text AS description,
  COALESCE(failure_category, '')::text AS failure_category,
  channels_json,
  deliveries_json,
  first_triggered_at,
  last_triggered_at,
  last_delivered_at,
  resolved_at,
  COALESCE(acknowledged_by, '')::text AS acknowledged_by,
  acknowledged_at,
  snoozed_until,
  COALESCE(suppression_reason, '')::text AS suppression_reason,
  created_at,
  updated_at
FROM alerts
ORDER BY last_triggered_at DESC
`

type ListAlertsRow struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	RunID             string           `json:"run_id"`
	Status            string           `json:"status"`
	Severity          string           `json:"severity"`
	Title             string           `json:"title"`
	Description       string           `json:"description"`
	FailureCategory   string           `json:"failure_category"`
	ChannelsJson      []byte           `json:"channels_json"`
	DeliveriesJson    []byte           `json:"deliveries_json"`
	FirstTriggeredAt  pgtype.Timestamp `json:"first_triggered_at"`
	LastTriggeredAt   pgtype.Timestamp `json:"last_triggered_at"`
	LastDeliveredAt   pgtype.Timestamp `json:"last_delivered_at"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	AcknowledgedBy    string           `json:"acknowledged_by"`
	AcknowledgedAt    pgtype.Timestamp `json:"acknowledged_at"`
	SnoozedUntil      pgtype.Timestamp `json:"snoozed_until"`
	SuppressionReason string           `json:"suppression_reason"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListAlerts(ctx context.Context) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.RunID,
			&i.Status,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.FailureCategory,
			&i.ChannelsJson,
			&i.DeliveriesJson,
			&i.FirstTriggeredAt,
			&i.LastTriggeredAt,
			&i.LastDeliveredAt,
			&i.ResolvedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.SnoozedUntil,
			&i.SuppressionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpenAlerts = `-- name: ResolveOpenAlerts :execrows
UPDATE alerts
SET status = $2, resolved_at = $3, updated_at = NOW()
WHERE monitor_id = $1 AND status = ANY($4::text[])
`

type ResolveOpenAlertsParams struct {
	MonitorID  pgtype.Text      `json:"monitor_id"`
	Status     pgtype.Text      `json:"status"`
	ResolvedAt pgtype.Timestamp `json:"resolved_at"`
	Column4    []string         `json:"column_4"`
}

func (q *Queries) ResolveOpenAlerts(ctx context.Context, arg ResolveOpenAlertsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveOpenAlerts,
		arg.MonitorID,
		arg.Status,
		arg.ResolvedAt,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAlert = `-- name: UpsertAlert :exec
INSERT INTO alerts (
  id,
  monitor_id,
  run_id,
  status,
  severity,
  title,
  description,
  failure_category,
  channels_json,
  deliveries_json,
  first_triggered_at,
  last_triggered_at,
  last_delivered_at,
  resolved_at,
  acknowledged_by,
  acknowledged_at,
  snoozed_until,
  suppression_reason,
  created_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $14,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $12,
  $13
)
ON CONFLICT (id) DO UPDATE SET
  run_id = EXCLUDED.run_id,
  status = EXCLUDED.status,
  severity = EXCLUDED.severity,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  failure_category = EXCLUDED.failure_category,
  channels_json = EXCLUDED.channels_json,
  deliveries_json = EXCLUDED.deliveries_json,
  last_triggered_at = EXCLUDED.last_triggered_at,
  last_delivered_at = EXCLUDED.last_delivered_at,
  resolved_at = EXCLUDED.resolved_at,
  acknowledged_by = EXCLUDED.acknowledged_by,
  acknowledged_at = EXCLUDED.acknowledged_at,
  snoozed_until = EXCLUDED.snoozed_until,
  suppression_reason = EXCLUDED.suppression_reason,
  updated_at = EXCLUDED.updated_at
`

type UpsertAlertParams struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	Status            pgtype.Text      `json:"status"`
	Severity          pgtype.Text      `json:"severity"`
	Title             pgtype.Text      `json:"title"`
	Description       pgtype.Text      `json:"description"`
	FailureCategory   pgtype.Text      `json:"failure_category"`
	ChannelsJson      []byte           `json:"channels_json"`
	DeliveriesJson    []byte           `json:"deliveries_json"`
	FirstTriggeredAt  pgtype.Timestamp `json:"first_triggered_at"`
	LastTriggeredAt   pgtype.Timestamp `json:"last_triggered_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	RunID             pgtype.Text      `json:"run_id"`
	LastDeliveredAt   pgtype.Timestamp `json:"last_delivered_at"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	AcknowledgedBy    pgtype.Text      `json:"acknowledged_by"`
	AcknowledgedAt    pgtype.Timestamp `json:"acknowledged_at"`
	SnoozedUntil      pgtype.Timestamp `json:"snoozed_until"`
	SuppressionReason pgtype.Text      `json:"suppression_reason"`
}

func (q *Queries) UpsertAlert(ctx context.Context, arg UpsertAlertParams) error {
	_, err := q.db.Exec(ctx, upsertAlert,
		arg.ID,
		arg.MonitorID,
		arg.Status,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.FailureCategory,
		arg.ChannelsJson,
		arg.DeliveriesJson,
		arg.FirstTriggeredAt,
		arg.LastTriggeredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.RunID,
		arg.LastDeliveredAt,
		arg.ResolvedAt,
		arg.AcknowledgedBy,
		arg.AcknowledgedAt,
		arg.SnoozedUntil,
		arg.SuppressionReason,
	)
	return err
}
