// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT
  id,
  name,
  car_id,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  log_field_mapping_json,
  COALESCE(description, '')::text AS description,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  tags_json,
  alert_routing_json,
  created_at,
  updated_at
FROM applications
WHERE id = $1
`

type GetApplicationRow struct {
	ID                  string           `json:"id"`
	Name                string           `json:"name"`
	CarID               string           `json:"car_id"`
	ElfAppID            string           `json:"elf_app_id"`
	IndexPathTemplate   string           `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	Description         string           `json:"description"`
	Owner               string           `json:"owner"`
	Environment         string           `json:"environment"`
	TagsJson            []byte           `json:"tags_json"`
	AlertRoutingJson    []byte           `json:"alert_routing_json"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetApplication(ctx context.Context, id string) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CarID,
		&i.ElfAppID,
		&i.IndexPathTemplate,
		&i.LogFieldMappingJson,
		&i.Description,
		&i.Owner,
		&i.Environment,
		&i.TagsJson,
		&i.AlertRoutingJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT
  id,
  name,
  car_id,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  log_field_mapping_json,
  COALESCE(description, '')::text AS description,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  tags_json,
  alert_routing_json,
  created_at,
  updated_at
FROM applications
ORDER BY name ASC
`

type ListApplicationsRow struct {
	ID                  string           `json:"id"`
	Name                string           `json:"name"`
	CarID               string           `json:"car_id"`
	ElfAppID            string           `json:"elf_app_id"`
	IndexPathTemplate   string           `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	Description         string           `json:"description"`
	Owner               string           `json:"owner"`
	Environment         string           `json:"environment"`
	TagsJson            []byte           `json:"tags_json"`
	AlertRoutingJson    []byte           `json:"alert_routing_json"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsRow{}
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CarID,
			&i.ElfAppID,
			&i.IndexPathTemplate,
			&i.LogFieldMappingJson,
			&i.Description,
			&i.Owner,
			&i.Environment,
			&i.TagsJson,
			&i.AlertRoutingJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO applications (
  id,
  name,
  car_id,
  elf_app_id,
  index_path_template,
  log_field_mapping_json,
  description,
  owner,
  environment,
  tags_json,
  alert_routing_json,
  created_at,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  car_id = EXCLUDED.car_id,
  elf_app_id = EXCLUDED.elf_app_id,
  index_path_template = EXCLUDED.index_path_template,
  log_field_mapping_json = EXCLUDED.log_field_mapping_json,
  description = EXCLUDED.description,
  owner = EXCLUDED.owner,
  environment = EXCLUDED.environment,
  tags_json = EXCLUDED.tags_json,
  alert_routing_json = EXCLUDED.alert_routing_json,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationParams struct {
	ID                  string           `json:"id"`
	Name                string           `json:"name"`
	CarID               string           `json:"car_id"`
	ElfAppID            pgtype.Text      `json:"elf_app_id"`
	IndexPathTemplate   pgtype.Text      `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	Description         pgtype.Text      `json:"description"`
	Owner               pgtype.Text      `json:"owner"`
	Environment         pgtype.Text      `json:"environment"`
	TagsJson            []byte           `json:"tags_json"`
	AlertRoutingJson    []byte           `json:"alert_routing_json"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertApplication,
		arg.ID,
		arg.Name,
		arg.CarID,
		arg.ElfAppID,
		arg.IndexPathTemplate,
		arg.LogFieldMappingJson,
		arg.Description,
		arg.Owner,
		arg.Environment,
		arg.TagsJson,
		arg.AlertRoutingJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
