// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApplicationService = `-- name: DeleteApplicationService :execrows
DELETE FROM application_services
WHERE id = $1
`

func (q *Queries) DeleteApplicationService(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplicationService = `-- name: GetApplicationService :one
SELECT
  id,
  application_id,
  name,
  log_service_name,
  COALESCE(squad, '')::text AS squad,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  log_field_mapping_json,
  is_active,
  created_at,
  updated_at
FROM application_services
WHERE id = $1
`

type GetApplicationServiceRow struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	LogServiceName      string           `json:"log_service_name"`
	Squad               string           `json:"squad"`
	Owner               string           `json:"owner"`
	Environment         string           `json:"environment"`
	ElfAppID            string           `json:"elf_app_id"`
	IndexPathTemplate   string           `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	IsActive            bool             `json:"is_active"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetApplicationService(ctx context.Context, id string) (GetApplicationServiceRow, error) {
	row := q.db.QueryRow(ctx, getApplicationService, id)
	var i GetApplicationServiceRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.LogServiceName,
		&i.Squad,
		&i.Owner,
		&i.Environment,
		&i.ElfAppID,
		&i.IndexPathTemplate,
		&i.LogFieldMappingJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationServices = `-- name: ListApplicationServices :many
SELECT
  id,
  application_id,
  name,
  log_service_name,
  COALESCE(squad, '')::text AS squad,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  log_field_mapping_json,
  is_active,
  created_at,
  updated_at
FROM application_services
WHERE application_id = $1
ORDER BY name ASC
`

type ListApplicationServicesRow struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	LogServiceName      string           `json:"log_service_name"`
	Squad               string           `json:"squad"`
	Owner               string           `json:"owner"`
	Environment         string           `json:"environment"`
	ElfAppID            string           `json:"elf_app_id"`
	IndexPathTemplate   string           `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	IsActive            bool             `json:"is_active"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListApplicationServices(ctx context.Context, applicationID string) ([]ListApplicationServicesRow, error) {
	rows, err := q.db.Query(ctx, listApplicationServices, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationServicesRow{}
	for rows.Next() {
		var i ListApplicationServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.LogServiceName,
			&i.Squad,
			&i.Owner,
			&i.Environment,
			&i.ElfAppID,
			&i.IndexPathTemplate,
			&i.LogFieldMappingJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplicationService = `-- name: UpsertApplicationService :exec
INSERT INTO application_services (
  id,
  application_id,
  name,
  log_service_name,
  squad,
  owner,
  environment,
  elf_app_id,
  index_path_template,
  log_field_mapping_json,
  is_active,
  created_at,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
ON CONFLICT (id) DO UPDATE SET
  application_id = EXCLUDED.application_id,
  name = EXCLUDED.name,
  log_service_name = EXCLUDED.log_service_name,
  squad = EXCLUDED.squad,
  owner = EXCLUDED.owner,
  environment = EXCLUDED.environment,
  elf_app_id = EXCLUDED.elf_app_id,
  index_path_template = EXCLUDED.index_path_template,
  log_field_mapping_json = EXCLUDED.log_field_mapping_json,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationServiceParams struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	LogServiceName      string           `json:"log_service_name"`
	Squad               pgtype.Text      `json:"squad"`
	Owner               pgtype.Text      `json:"owner"`
	Environment         pgtype.Text      `json:"environment"`
	ElfAppID            pgtype.Text      `json:"elf_app_id"`
	IndexPathTemplate   pgtype.Text      `json:"index_path_template"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	IsActive            bool             `json:"is_active"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertApplicationService(ctx context.Context, arg UpsertApplicationServiceParams) error {
	_, err := q.db.Exec(ctx, upsertApplicationService,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.LogServiceName,
		arg.Squad,
		arg.Owner,
		arg.Environment,
		arg.ElfAppID,
		arg.IndexPathTemplate,
		arg.LogFieldMappingJson,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
