// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM applications
WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT
  id,
  name,
  car_id,
  COALESCE(description, '')::text AS description,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  tags_json,
  created_at,
  updated_at
FROM applications
WHERE id = $1
`

type GetApplicationRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	CarID       string           `json:"car_id"`
	Description string           `json:"description"`
	Owner       string           `json:"owner"`
	Environment string           `json:"environment"`
	TagsJson    []byte           `json:"tags_json"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetApplication(ctx context.Context, id string) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CarID,
		&i.Description,
		&i.Owner,
		&i.Environment,
		&i.TagsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT
  id,
  name,
  car_id,
  COALESCE(description, '')::text AS description,
  COALESCE(owner, '')::text AS owner,
  COALESCE(environment, '')::text AS environment,
  tags_json,
  created_at,
  updated_at
FROM applications
ORDER BY name ASC
`

type ListApplicationsRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	CarID       string           `json:"car_id"`
	Description string           `json:"description"`
	Owner       string           `json:"owner"`
	Environment string           `json:"environment"`
	TagsJson    []byte           `json:"tags_json"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsRow{}
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CarID,
			&i.Description,
			&i.Owner,
			&i.Environment,
			&i.TagsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO applications (
  id,
  name,
  car_id,
  description,
  owner,
  environment,
  tags_json,
  created_at,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  car_id = EXCLUDED.car_id,
  description = EXCLUDED.description,
  owner = EXCLUDED.owner,
  environment = EXCLUDED.environment,
  tags_json = EXCLUDED.tags_json,
  updated_at = EXCLUDED.updated_at
`

type UpsertApplicationParams struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	CarID       string           `json:"car_id"`
	Description pgtype.Text      `json:"description"`
	Owner       pgtype.Text      `json:"owner"`
	Environment pgtype.Text      `json:"environment"`
	TagsJson    []byte           `json:"tags_json"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertApplication,
		arg.ID,
		arg.Name,
		arg.CarID,
		arg.Description,
		arg.Owner,
		arg.Environment,
		arg.TagsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
