// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCertificateProfile = `-- name: DeleteCertificateProfile :execrows
DELETE FROM certificate_profiles
WHERE id = $1
`

func (q *Queries) DeleteCertificateProfile(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertificateProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertificateProfile = `-- name: GetCertificateProfile :one
SELECT
  id,
  name,
  host,
  port,
  cert_type,
  COALESCE(cert_secret_alias, '')::text AS cert_secret_alias,
  COALESCE(key_secret_alias, '')::text AS key_secret_alias,
  COALESCE(pfx_secret_alias, '')::text AS pfx_secret_alias,
  COALESCE(ca_cert_secret_alias, '')::text AS ca_cert_secret_alias,
  COALESCE(passphrase_secret_alias, '')::text AS passphrase_secret_alias,
  insecure_skip_verify,
  is_active,
  last_tested_at,
  created_at,
  updated_at
FROM certificate_profiles
WHERE id = $1
`

type GetCertificateProfileRow struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	Host                  string           `json:"host"`
	Port                  int32            `json:"port"`
	CertType              string           `json:"cert_type"`
	CertSecretAlias       string           `json:"cert_secret_alias"`
	KeySecretAlias        string           `json:"key_secret_alias"`
	PfxSecretAlias        string           `json:"pfx_secret_alias"`
	CaCertSecretAlias     string           `json:"ca_cert_secret_alias"`
	PassphraseSecretAlias string           `json:"passphrase_secret_alias"`
	InsecureSkipVerify    pgtype.Bool      `json:"insecure_skip_verify"`
	IsActive              pgtype.Bool      `json:"is_active"`
	LastTestedAt          pgtype.Timestamp `json:"last_tested_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetCertificateProfile(ctx context.Context, id string) (GetCertificateProfileRow, error) {
	row := q.db.QueryRow(ctx, getCertificateProfile, id)
	var i GetCertificateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.CertType,
		&i.CertSecretAlias,
		&i.KeySecretAlias,
		&i.PfxSecretAlias,
		&i.CaCertSecretAlias,
		&i.PassphraseSecretAlias,
		&i.InsecureSkipVerify,
		&i.IsActive,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificateProfiles = `-- name: ListCertificateProfiles :many
SELECT
  id,
  name,
  host,
  port,
  cert_type,
  COALESCE(cert_secret_alias, '')::text AS cert_secret_alias,
  COALESCE(key_secret_alias, '')::text AS key_secret_alias,
  COALESCE(pfx_secret_alias, '')::text AS pfx_secret_alias,
  COALESCE(ca_cert_secret_alias, '')::text AS ca_cert_secret_alias,
  COALESCE(passphrase_secret_alias, '')::text AS passphrase_secret_alias,
  insecure_skip_verify,
  is_active,
  last_tested_at,
  created_at,
  updated_at
FROM certificate_profiles
ORDER BY updated_at DESC
`

type ListCertificateProfilesRow struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	Host                  string           `json:"host"`
	Port                  int32            `json:"port"`
	CertType              string           `json:"cert_type"`
	CertSecretAlias       string           `json:"cert_secret_alias"`
	KeySecretAlias        string           `json:"key_secret_alias"`
	PfxSecretAlias        string           `json:"pfx_secret_alias"`
	CaCertSecretAlias     string           `json:"ca_cert_secret_alias"`
	PassphraseSecretAlias string           `json:"passphrase_secret_alias"`
	InsecureSkipVerify    pgtype.Bool      `json:"insecure_skip_verify"`
	IsActive              pgtype.Bool      `json:"is_active"`
	LastTestedAt          pgtype.Timestamp `json:"last_tested_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListCertificateProfiles(ctx context.Context) ([]ListCertificateProfilesRow, error) {
	rows, err := q.db.Query(ctx, listCertificateProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateProfilesRow{}
	for rows.Next() {
		var i ListCertificateProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.CertType,
			&i.CertSecretAlias,
			&i.KeySecretAlias,
			&i.PfxSecretAlias,
			&i.CaCertSecretAlias,
			&i.PassphraseSecretAlias,
			&i.InsecureSkipVerify,
			&i.IsActive,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCertificateProfile = `-- name: UpsertCertificateProfile :exec
INSERT INTO certificate_profiles (
  id,
  name,
  host,
  port,
  cert_type,
  cert_secret_alias,
  key_secret_alias,
  pfx_secret_alias,
  ca_cert_secret_alias,
  passphrase_secret_alias,
  insecure_skip_verify,
  is_active,
  last_tested_at,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $8,
  $9,
  $10,
  $11,
  $12,
  $6,
  $7,
  $13,
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  host = EXCLUDED.host,
  port = EXCLUDED.port,
  cert_type = EXCLUDED.cert_type,
  cert_secret_alias = EXCLUDED.cert_secret_alias,
  key_secret_alias = EXCLUDED.key_secret_alias,
  pfx_secret_alias = EXCLUDED.pfx_secret_alias,
  ca_cert_secret_alias = EXCLUDED.ca_cert_secret_alias,
  passphrase_secret_alias = EXCLUDED.passphrase_secret_alias,
  insecure_skip_verify = EXCLUDED.insecure_skip_verify,
  is_active = EXCLUDED.is_active,
  last_tested_at = COALESCE(EXCLUDED.last_tested_at, certificate_profiles.last_tested_at),
  updated_at = NOW()
`

type UpsertCertificateProfileParams struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	Host                  string           `json:"host"`
	Port                  int32            `json:"port"`
	CertType              string           `json:"cert_type"`
	InsecureSkipVerify    pgtype.Bool      `json:"insecure_skip_verify"`
	IsActive              pgtype.Bool      `json:"is_active"`
	CertSecretAlias       pgtype.Text      `json:"cert_secret_alias"`
	KeySecretAlias        pgtype.Text      `json:"key_secret_alias"`
	PfxSecretAlias        pgtype.Text      `json:"pfx_secret_alias"`
	CaCertSecretAlias     pgtype.Text      `json:"ca_cert_secret_alias"`
	PassphraseSecretAlias pgtype.Text      `json:"passphrase_secret_alias"`
	LastTestedAt          pgtype.Timestamp `json:"last_tested_at"`
}

func (q *Queries) UpsertCertificateProfile(ctx context.Context, arg UpsertCertificateProfileParams) error {
	_, err := q.db.Exec(ctx, upsertCertificateProfile,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.CertType,
		arg.InsecureSkipVerify,
		arg.IsActive,
		arg.CertSecretAlias,
		arg.KeySecretAlias,
		arg.PfxSecretAlias,
		arg.CaCertSecretAlias,
		arg.PassphraseSecretAlias,
		arg.LastTestedAt,
	)
	return err
}
