// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_validations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeploymentValidation = `-- name: DeleteDeploymentValidation :execrows
DELETE FROM deployment_validations
WHERE id = $1
`

func (q *Queries) DeleteDeploymentValidation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeploymentValidation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeploymentValidation = `-- name: GetDeploymentValidation :one
SELECT
  id,
  COALESCE(application_id, '')::text AS application_id,
  application_name,
  car_id,
  name,
  COALESCE(version, '')::text AS version,
  COALESCE(build_id, '')::text AS build_id,
  COALESCE(environment, '')::text AS environment,
  status,
  monitor_ids_json,
  report_json,
  COALESCE(ai_report_json, '{}'::jsonb) AS ai_report_json,
  COALESCE(sample_count, 1)::int AS sample_count,
  COALESCE(interval_seconds, 0)::int AS interval_seconds,
  deployment_started_at,
  COALESCE(baseline_window_hours, 24)::int AS baseline_window_hours,
  COALESCE(baseline_run_count, 30)::int AS baseline_run_count,
  pre_started_at,
  pre_completed_at,
  post_started_at,
  post_completed_at,
  COALESCE(elf_query_ids_json, '[]'::jsonb) AS elf_query_ids_json,
  COALESCE(auto_run_log_check, FALSE) AS auto_run_log_check,
  COALESCE(service_ids_json, '[]'::jsonb) AS service_ids_json,
  COALESCE(observability_profile, 'standard')::text AS observability_profile,
  COALESCE(signal_pack_ids_json, '[]'::jsonb) AS signal_pack_ids_json,
  COALESCE(elf_results_json, '[]'::jsonb) AS elf_results_json,
  log_started_at,
  log_completed_at,
  created_at,
  updated_at
FROM deployment_validations
WHERE id = $1
`

type GetDeploymentValidationRow struct {
	ID                   string           `json:"id"`
	ApplicationID        string           `json:"application_id"`
	ApplicationName      string           `json:"application_name"`
	CarID                string           `json:"car_id"`
	Name                 string           `json:"name"`
	Version              string           `json:"version"`
	BuildID              string           `json:"build_id"`
	Environment          string           `json:"environment"`
	Status               string           `json:"status"`
	MonitorIdsJson       []byte           `json:"monitor_ids_json"`
	ReportJson           []byte           `json:"report_json"`
	AiReportJson         []byte           `json:"ai_report_json"`
	SampleCount          int32            `json:"sample_count"`
	IntervalSeconds      int32            `json:"interval_seconds"`
	DeploymentStartedAt  pgtype.Timestamp `json:"deployment_started_at"`
	BaselineWindowHours  int32            `json:"baseline_window_hours"`
	BaselineRunCount     int32            `json:"baseline_run_count"`
	PreStartedAt         pgtype.Timestamp `json:"pre_started_at"`
	PreCompletedAt       pgtype.Timestamp `json:"pre_completed_at"`
	PostStartedAt        pgtype.Timestamp `json:"post_started_at"`
	PostCompletedAt      pgtype.Timestamp `json:"post_completed_at"`
	ElfQueryIdsJson      []byte           `json:"elf_query_ids_json"`
	AutoRunLogCheck      bool             `json:"auto_run_log_check"`
	ServiceIdsJson       []byte           `json:"service_ids_json"`
	ObservabilityProfile string           `json:"observability_profile"`
	SignalPackIdsJson    []byte           `json:"signal_pack_ids_json"`
	ElfResultsJson       []byte           `json:"elf_results_json"`
	LogStartedAt         pgtype.Timestamp `json:"log_started_at"`
	LogCompletedAt       pgtype.Timestamp `json:"log_completed_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetDeploymentValidation(ctx context.Context, id string) (GetDeploymentValidationRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentValidation, id)
	var i GetDeploymentValidationRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ApplicationName,
		&i.CarID,
		&i.Name,
		&i.Version,
		&i.BuildID,
		&i.Environment,
		&i.Status,
		&i.MonitorIdsJson,
		&i.ReportJson,
		&i.AiReportJson,
		&i.SampleCount,
		&i.IntervalSeconds,
		&i.DeploymentStartedAt,
		&i.BaselineWindowHours,
		&i.BaselineRunCount,
		&i.PreStartedAt,
		&i.PreCompletedAt,
		&i.PostStartedAt,
		&i.PostCompletedAt,
		&i.ElfQueryIdsJson,
		&i.AutoRunLogCheck,
		&i.ServiceIdsJson,
		&i.ObservabilityProfile,
		&i.SignalPackIdsJson,
		&i.ElfResultsJson,
		&i.LogStartedAt,
		&i.LogCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkDeploymentValidationRun = `-- name: LinkDeploymentValidationRun :exec
INSERT INTO deployment_validation_runs (
  validation_id,
  phase,
  monitor_id,
  run_id
)
VALUES ($1,$2,$3,$4)
ON CONFLICT DO NOTHING
`

type LinkDeploymentValidationRunParams struct {
	ValidationID string `json:"validation_id"`
	Phase        string `json:"phase"`
	MonitorID    string `json:"monitor_id"`
	RunID        string `json:"run_id"`
}

func (q *Queries) LinkDeploymentValidationRun(ctx context.Context, arg LinkDeploymentValidationRunParams) error {
	_, err := q.db.Exec(ctx, linkDeploymentValidationRun,
		arg.ValidationID,
		arg.Phase,
		arg.MonitorID,
		arg.RunID,
	)
	return err
}

const listDeploymentValidationRuns = `-- name: ListDeploymentValidationRuns :many
SELECT
  r.id,
  r.monitor_id,
  COALESCE(m.name, '')::text AS monitor_name,
  COALESCE(r.status, '')::text AS status,
  COALESCE(r.failure_category, '')::text AS failure_category,
  COALESCE(r.failure_reason, '')::text AS failure_reason,
  COALESCE(r.triggered_by, '')::text AS triggered_by,
  r.started_at,
  r.ended_at,
  COALESCE(r.duration_ms, 0)::int AS duration_ms
FROM deployment_validation_runs l
INNER JOIN monitor_runs r ON r.id = l.run_id
LEFT JOIN monitors m ON m.id = r.monitor_id
WHERE l.validation_id = $1 AND l.phase = $2
ORDER BY r.started_at DESC
`

type ListDeploymentValidationRunsParams struct {
	ValidationID string `json:"validation_id"`
	Phase        string `json:"phase"`
}

type ListDeploymentValidationRunsRow struct {
	ID              string           `json:"id"`
	MonitorID       pgtype.Text      `json:"monitor_id"`
	MonitorName     string           `json:"monitor_name"`
	Status          string           `json:"status"`
	FailureCategory string           `json:"failure_category"`
	FailureReason   string           `json:"failure_reason"`
	TriggeredBy     string           `json:"triggered_by"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	DurationMs      int32            `json:"duration_ms"`
}

func (q *Queries) ListDeploymentValidationRuns(ctx context.Context, arg ListDeploymentValidationRunsParams) ([]ListDeploymentValidationRunsRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentValidationRuns, arg.ValidationID, arg.Phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentValidationRunsRow{}
	for rows.Next() {
		var i ListDeploymentValidationRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.MonitorName,
			&i.Status,
			&i.FailureCategory,
			&i.FailureReason,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentValidations = `-- name: ListDeploymentValidations :many
SELECT
  id,
  COALESCE(application_id, '')::text AS application_id,
  application_name,
  car_id,
  name,
  COALESCE(version, '')::text AS version,
  COALESCE(build_id, '')::text AS build_id,
  COALESCE(environment, '')::text AS environment,
  status,
  monitor_ids_json,
  report_json,
  COALESCE(ai_report_json, '{}'::jsonb) AS ai_report_json,
  COALESCE(sample_count, 1)::int AS sample_count,
  COALESCE(interval_seconds, 0)::int AS interval_seconds,
  deployment_started_at,
  COALESCE(baseline_window_hours, 24)::int AS baseline_window_hours,
  COALESCE(baseline_run_count, 30)::int AS baseline_run_count,
  pre_started_at,
  pre_completed_at,
  post_started_at,
  post_completed_at,
  COALESCE(elf_query_ids_json, '[]'::jsonb) AS elf_query_ids_json,
  COALESCE(auto_run_log_check, FALSE) AS auto_run_log_check,
  COALESCE(service_ids_json, '[]'::jsonb) AS service_ids_json,
  COALESCE(observability_profile, 'standard')::text AS observability_profile,
  COALESCE(signal_pack_ids_json, '[]'::jsonb) AS signal_pack_ids_json,
  COALESCE(elf_results_json, '[]'::jsonb) AS elf_results_json,
  log_started_at,
  log_completed_at,
  created_at,
  updated_at
FROM deployment_validations
WHERE $1::text IS NULL OR application_id = $1
ORDER BY created_at DESC
`

type ListDeploymentValidationsRow struct {
	ID                   string           `json:"id"`
	ApplicationID        string           `json:"application_id"`
	ApplicationName      string           `json:"application_name"`
	CarID                string           `json:"car_id"`
	Name                 string           `json:"name"`
	Version              string           `json:"version"`
	BuildID              string           `json:"build_id"`
	Environment          string           `json:"environment"`
	Status               string           `json:"status"`
	MonitorIdsJson       []byte           `json:"monitor_ids_json"`
	ReportJson           []byte           `json:"report_json"`
	AiReportJson         []byte           `json:"ai_report_json"`
	SampleCount          int32            `json:"sample_count"`
	IntervalSeconds      int32            `json:"interval_seconds"`
	DeploymentStartedAt  pgtype.Timestamp `json:"deployment_started_at"`
	BaselineWindowHours  int32            `json:"baseline_window_hours"`
	BaselineRunCount     int32            `json:"baseline_run_count"`
	PreStartedAt         pgtype.Timestamp `json:"pre_started_at"`
	PreCompletedAt       pgtype.Timestamp `json:"pre_completed_at"`
	PostStartedAt        pgtype.Timestamp `json:"post_started_at"`
	PostCompletedAt      pgtype.Timestamp `json:"post_completed_at"`
	ElfQueryIdsJson      []byte           `json:"elf_query_ids_json"`
	AutoRunLogCheck      bool             `json:"auto_run_log_check"`
	ServiceIdsJson       []byte           `json:"service_ids_json"`
	ObservabilityProfile string           `json:"observability_profile"`
	SignalPackIdsJson    []byte           `json:"signal_pack_ids_json"`
	ElfResultsJson       []byte           `json:"elf_results_json"`
	LogStartedAt         pgtype.Timestamp `json:"log_started_at"`
	LogCompletedAt       pgtype.Timestamp `json:"log_completed_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListDeploymentValidations(ctx context.Context, applicationID pgtype.Text) ([]ListDeploymentValidationsRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentValidations, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentValidationsRow{}
	for rows.Next() {
		var i ListDeploymentValidationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ApplicationName,
			&i.CarID,
			&i.Name,
			&i.Version,
			&i.BuildID,
			&i.Environment,
			&i.Status,
			&i.MonitorIdsJson,
			&i.ReportJson,
			&i.AiReportJson,
			&i.SampleCount,
			&i.IntervalSeconds,
			&i.DeploymentStartedAt,
			&i.BaselineWindowHours,
			&i.BaselineRunCount,
			&i.PreStartedAt,
			&i.PreCompletedAt,
			&i.PostStartedAt,
			&i.PostCompletedAt,
			&i.ElfQueryIdsJson,
			&i.AutoRunLogCheck,
			&i.ServiceIdsJson,
			&i.ObservabilityProfile,
			&i.SignalPackIdsJson,
			&i.ElfResultsJson,
			&i.LogStartedAt,
			&i.LogCompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeploymentValidation = `-- name: UpsertDeploymentValidation :exec
INSERT INTO deployment_validations (
  id,
  application_id,
  application_name,
  car_id,
  name,
  version,
  build_id,
  environment,
  status,
  monitor_ids_json,
  report_json,
  ai_report_json,
  sample_count,
  interval_seconds,
  deployment_started_at,
  baseline_window_hours,
  baseline_run_count,
  pre_started_at,
  pre_completed_at,
  post_started_at,
  post_completed_at,
  elf_query_ids_json,
  auto_run_log_check,
  service_ids_json,
  observability_profile,
  signal_pack_ids_json,
  elf_results_json,
  log_started_at,
  log_completed_at,
  created_at,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31)
ON CONFLICT (id) DO UPDATE SET
  application_id = EXCLUDED.application_id,
  application_name = EXCLUDED.application_name,
  car_id = EXCLUDED.car_id,
  name = EXCLUDED.name,
  version = EXCLUDED.version,
  build_id = EXCLUDED.build_id,
  environment = EXCLUDED.environment,
  status = EXCLUDED.status,
  monitor_ids_json = EXCLUDED.monitor_ids_json,
  report_json = EXCLUDED.report_json,
  ai_report_json = EXCLUDED.ai_report_json,
  sample_count = EXCLUDED.sample_count,
  interval_seconds = EXCLUDED.interval_seconds,
  deployment_started_at = EXCLUDED.deployment_started_at,
  baseline_window_hours = EXCLUDED.baseline_window_hours,
  baseline_run_count = EXCLUDED.baseline_run_count,
  pre_started_at = EXCLUDED.pre_started_at,
  pre_completed_at = EXCLUDED.pre_completed_at,
  post_started_at = EXCLUDED.post_started_at,
  post_completed_at = EXCLUDED.post_completed_at,
  elf_query_ids_json = EXCLUDED.elf_query_ids_json,
  auto_run_log_check = EXCLUDED.auto_run_log_check,
  service_ids_json = EXCLUDED.service_ids_json,
  observability_profile = EXCLUDED.observability_profile,
  signal_pack_ids_json = EXCLUDED.signal_pack_ids_json,
  elf_results_json = EXCLUDED.elf_results_json,
  log_started_at = EXCLUDED.log_started_at,
  log_completed_at = EXCLUDED.log_completed_at,
  updated_at = EXCLUDED.updated_at
`

type UpsertDeploymentValidationParams struct {
	ID                   string           `json:"id"`
	ApplicationID        pgtype.Text      `json:"application_id"`
	ApplicationName      string           `json:"application_name"`
	CarID                string           `json:"car_id"`
	Name                 string           `json:"name"`
	Version              pgtype.Text      `json:"version"`
	BuildID              pgtype.Text      `json:"build_id"`
	Environment          pgtype.Text      `json:"environment"`
	Status               string           `json:"status"`
	MonitorIdsJson       []byte           `json:"monitor_ids_json"`
	ReportJson           []byte           `json:"report_json"`
	AiReportJson         []byte           `json:"ai_report_json"`
	SampleCount          int32            `json:"sample_count"`
	IntervalSeconds      int32            `json:"interval_seconds"`
	DeploymentStartedAt  pgtype.Timestamp `json:"deployment_started_at"`
	BaselineWindowHours  int32            `json:"baseline_window_hours"`
	BaselineRunCount     int32            `json:"baseline_run_count"`
	PreStartedAt         pgtype.Timestamp `json:"pre_started_at"`
	PreCompletedAt       pgtype.Timestamp `json:"pre_completed_at"`
	PostStartedAt        pgtype.Timestamp `json:"post_started_at"`
	PostCompletedAt      pgtype.Timestamp `json:"post_completed_at"`
	ElfQueryIdsJson      []byte           `json:"elf_query_ids_json"`
	AutoRunLogCheck      bool             `json:"auto_run_log_check"`
	ServiceIdsJson       []byte           `json:"service_ids_json"`
	ObservabilityProfile string           `json:"observability_profile"`
	SignalPackIdsJson    []byte           `json:"signal_pack_ids_json"`
	ElfResultsJson       []byte           `json:"elf_results_json"`
	LogStartedAt         pgtype.Timestamp `json:"log_started_at"`
	LogCompletedAt       pgtype.Timestamp `json:"log_completed_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertDeploymentValidation(ctx context.Context, arg UpsertDeploymentValidationParams) error {
	_, err := q.db.Exec(ctx, upsertDeploymentValidation,
		arg.ID,
		arg.ApplicationID,
		arg.ApplicationName,
		arg.CarID,
		arg.Name,
		arg.Version,
		arg.BuildID,
		arg.Environment,
		arg.Status,
		arg.MonitorIdsJson,
		arg.ReportJson,
		arg.AiReportJson,
		arg.SampleCount,
		arg.IntervalSeconds,
		arg.DeploymentStartedAt,
		arg.BaselineWindowHours,
		arg.BaselineRunCount,
		arg.PreStartedAt,
		arg.PreCompletedAt,
		arg.PostStartedAt,
		arg.PostCompletedAt,
		arg.ElfQueryIdsJson,
		arg.AutoRunLogCheck,
		arg.ServiceIdsJson,
		arg.ObservabilityProfile,
		arg.SignalPackIdsJson,
		arg.ElfResultsJson,
		arg.LogStartedAt,
		arg.LogCompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
