// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: elf_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteElfQuery = `-- name: DeleteElfQuery :execrows
DELETE FROM elf_queries
WHERE id = $1
`

func (q *Queries) DeleteElfQuery(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteElfQuery, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getElfQuery = `-- name: GetElfQuery :one
SELECT
  id,
  name,
  COALESCE(description, '')::text AS description,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  search_body_json,
  gate_mode,
  pass_criteria_json,
  COALESCE(application_id, '')::text AS application_id,
  COALESCE(signal_type, 'custom')::text AS signal_type,
  comparison_config_json,
  COALESCE(service_id, '')::text AS service_id,
  probe_config_json,
  field_mapping_json,
  field_schema_json,
  COALESCE(check_kind, 'raw')::text AS check_kind,
  check_config_json,
  generated_search_body_json,
  last_probe_at,
  last_probe_summary_json,
  tags_json,
  is_active,
  created_at,
  updated_at
FROM elf_queries
WHERE id = $1
`

type GetElfQueryRow struct {
	ID                       string           `json:"id"`
	Name                     string           `json:"name"`
	Description              string           `json:"description"`
	ElfAppID                 string           `json:"elf_app_id"`
	IndexPathTemplate        string           `json:"index_path_template"`
	SearchBodyJson           []byte           `json:"search_body_json"`
	GateMode                 string           `json:"gate_mode"`
	PassCriteriaJson         []byte           `json:"pass_criteria_json"`
	ApplicationID            string           `json:"application_id"`
	SignalType               string           `json:"signal_type"`
	ComparisonConfigJson     []byte           `json:"comparison_config_json"`
	ServiceID                string           `json:"service_id"`
	ProbeConfigJson          []byte           `json:"probe_config_json"`
	FieldMappingJson         []byte           `json:"field_mapping_json"`
	FieldSchemaJson          []byte           `json:"field_schema_json"`
	CheckKind                string           `json:"check_kind"`
	CheckConfigJson          []byte           `json:"check_config_json"`
	GeneratedSearchBodyJson  []byte           `json:"generated_search_body_json"`
	LastProbeAt              pgtype.Timestamp `json:"last_probe_at"`
	LastProbeSummaryJson     []byte           `json:"last_probe_summary_json"`
	TagsJson                 []byte           `json:"tags_json"`
	IsActive                 bool             `json:"is_active"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetElfQuery(ctx context.Context, id string) (GetElfQueryRow, error) {
	row := q.db.QueryRow(ctx, getElfQuery, id)
	var i GetElfQueryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ElfAppID,
		&i.IndexPathTemplate,
		&i.SearchBodyJson,
		&i.GateMode,
		&i.PassCriteriaJson,
		&i.ApplicationID,
		&i.SignalType,
		&i.ComparisonConfigJson,
		&i.ServiceID,
		&i.ProbeConfigJson,
		&i.FieldMappingJson,
		&i.FieldSchemaJson,
		&i.CheckKind,
		&i.CheckConfigJson,
		&i.GeneratedSearchBodyJson,
		&i.LastProbeAt,
		&i.LastProbeSummaryJson,
		&i.TagsJson,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listElfQueries = `-- name: ListElfQueries :many
SELECT
  id,
  name,
  COALESCE(description, '')::text AS description,
  COALESCE(elf_app_id, '')::text AS elf_app_id,
  COALESCE(index_path_template, '')::text AS index_path_template,
  search_body_json,
  gate_mode,
  pass_criteria_json,
  COALESCE(application_id, '')::text AS application_id,
  COALESCE(signal_type, 'custom')::text AS signal_type,
  comparison_config_json,
  COALESCE(service_id, '')::text AS service_id,
  probe_config_json,
  field_mapping_json,
  field_schema_json,
  COALESCE(check_kind, 'raw')::text AS check_kind,
  check_config_json,
  generated_search_body_json,
  last_probe_at,
  last_probe_summary_json,
  tags_json,
  is_active,
  created_at,
  updated_at
FROM elf_queries
WHERE $1::text IS NULL OR application_id = $1
ORDER BY name ASC
`

type ListElfQueriesRow struct {
	ID                       string           `json:"id"`
	Name                     string           `json:"name"`
	Description              string           `json:"description"`
	ElfAppID                 string           `json:"elf_app_id"`
	IndexPathTemplate        string           `json:"index_path_template"`
	SearchBodyJson           []byte           `json:"search_body_json"`
	GateMode                 string           `json:"gate_mode"`
	PassCriteriaJson         []byte           `json:"pass_criteria_json"`
	ApplicationID            string           `json:"application_id"`
	SignalType               string           `json:"signal_type"`
	ComparisonConfigJson     []byte           `json:"comparison_config_json"`
	ServiceID                string           `json:"service_id"`
	ProbeConfigJson          []byte           `json:"probe_config_json"`
	FieldMappingJson         []byte           `json:"field_mapping_json"`
	FieldSchemaJson          []byte           `json:"field_schema_json"`
	CheckKind                string           `json:"check_kind"`
	CheckConfigJson          []byte           `json:"check_config_json"`
	GeneratedSearchBodyJson  []byte           `json:"generated_search_body_json"`
	LastProbeAt              pgtype.Timestamp `json:"last_probe_at"`
	LastProbeSummaryJson     []byte           `json:"last_probe_summary_json"`
	TagsJson                 []byte           `json:"tags_json"`
	IsActive                 bool             `json:"is_active"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListElfQueries(ctx context.Context, applicationID pgtype.Text) ([]ListElfQueriesRow, error) {
	rows, err := q.db.Query(ctx, listElfQueries, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListElfQueriesRow{}
	for rows.Next() {
		var i ListElfQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ElfAppID,
			&i.IndexPathTemplate,
			&i.SearchBodyJson,
			&i.GateMode,
			&i.PassCriteriaJson,
			&i.ApplicationID,
			&i.SignalType,
			&i.ComparisonConfigJson,
			&i.ServiceID,
			&i.ProbeConfigJson,
			&i.FieldMappingJson,
			&i.FieldSchemaJson,
			&i.CheckKind,
			&i.CheckConfigJson,
			&i.GeneratedSearchBodyJson,
			&i.LastProbeAt,
			&i.LastProbeSummaryJson,
			&i.TagsJson,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertElfQuery = `-- name: UpsertElfQuery :exec
INSERT INTO elf_queries (
  id,
  name,
  description,
  elf_app_id,
  index_path_template,
  search_body_json,
  gate_mode,
  pass_criteria_json,
  application_id,
  signal_type,
  comparison_config_json,
  service_id,
  probe_config_json,
  field_mapping_json,
  field_schema_json,
  check_kind,
  check_config_json,
  generated_search_body_json,
  last_probe_at,
  last_probe_summary_json,
  tags_json,
  is_active,
  created_at,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  elf_app_id = EXCLUDED.elf_app_id,
  index_path_template = EXCLUDED.index_path_template,
  search_body_json = EXCLUDED.search_body_json,
  gate_mode = EXCLUDED.gate_mode,
  pass_criteria_json = EXCLUDED.pass_criteria_json,
  application_id = EXCLUDED.application_id,
  signal_type = EXCLUDED.signal_type,
  comparison_config_json = EXCLUDED.comparison_config_json,
  service_id = EXCLUDED.service_id,
  probe_config_json = EXCLUDED.probe_config_json,
  field_mapping_json = EXCLUDED.field_mapping_json,
  field_schema_json = EXCLUDED.field_schema_json,
  check_kind = EXCLUDED.check_kind,
  check_config_json = EXCLUDED.check_config_json,
  generated_search_body_json = EXCLUDED.generated_search_body_json,
  last_probe_at = EXCLUDED.last_probe_at,
  last_probe_summary_json = EXCLUDED.last_probe_summary_json,
  tags_json = EXCLUDED.tags_json,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at
`

type UpsertElfQueryParams struct {
	ID                      string           `json:"id"`
	Name                    string           `json:"name"`
	Description             pgtype.Text      `json:"description"`
	ElfAppID                pgtype.Text      `json:"elf_app_id"`
	IndexPathTemplate       pgtype.Text      `json:"index_path_template"`
	SearchBodyJson          []byte           `json:"search_body_json"`
	GateMode                string           `json:"gate_mode"`
	PassCriteriaJson        []byte           `json:"pass_criteria_json"`
	ApplicationID           pgtype.Text      `json:"application_id"`
	SignalType              string           `json:"signal_type"`
	ComparisonConfigJson    []byte           `json:"comparison_config_json"`
	ServiceID               pgtype.Text      `json:"service_id"`
	ProbeConfigJson         []byte           `json:"probe_config_json"`
	FieldMappingJson        []byte           `json:"field_mapping_json"`
	FieldSchemaJson         []byte           `json:"field_schema_json"`
	CheckKind               string           `json:"check_kind"`
	CheckConfigJson         []byte           `json:"check_config_json"`
	GeneratedSearchBodyJson []byte           `json:"generated_search_body_json"`
	LastProbeAt             pgtype.Timestamp `json:"last_probe_at"`
	LastProbeSummaryJson    []byte           `json:"last_probe_summary_json"`
	TagsJson                []byte           `json:"tags_json"`
	IsActive                bool             `json:"is_active"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertElfQuery(ctx context.Context, arg UpsertElfQueryParams) error {
	_, err := q.db.Exec(ctx, upsertElfQuery,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ElfAppID,
		arg.IndexPathTemplate,
		arg.SearchBodyJson,
		arg.GateMode,
		arg.PassCriteriaJson,
		arg.ApplicationID,
		arg.SignalType,
		arg.ComparisonConfigJson,
		arg.ServiceID,
		arg.ProbeConfigJson,
		arg.FieldMappingJson,
		arg.FieldSchemaJson,
		arg.CheckKind,
		arg.CheckConfigJson,
		arg.GeneratedSearchBodyJson,
		arg.LastProbeAt,
		arg.LastProbeSummaryJson,
		arg.TagsJson,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
