// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :execrows
DELETE FROM alert_maintenance_windows
WHERE id = $1
`

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenanceWindow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveMaintenanceWindows = `-- name: ListActiveMaintenanceWindows :many
SELECT
  id,
  scope_type,
  COALESCE(scope_id, '')::text AS scope_id,
  starts_at,
  ends_at,
  COALESCE(reason, '')::text AS reason,
  COALESCE(created_by, '')::text AS created_by,
  created_at
FROM alert_maintenance_windows
WHERE starts_at <= $1 AND ends_at > $1
ORDER BY ends_at DESC
`

type ListActiveMaintenanceWindowsRow struct {
	ID        string           `json:"id"`
	ScopeType string           `json:"scope_type"`
	ScopeID   string           `json:"scope_id"`
	StartsAt  pgtype.Timestamp `json:"starts_at"`
	EndsAt    pgtype.Timestamp `json:"ends_at"`
	Reason    string           `json:"reason"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListActiveMaintenanceWindows(ctx context.Context, startsAt pgtype.Timestamp) ([]ListActiveMaintenanceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listActiveMaintenanceWindows, startsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMaintenanceWindowsRow{}
	for rows.Next() {
		var i ListActiveMaintenanceWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT
  id,
  scope_type,
  COALESCE(scope_id, '')::text AS scope_id,
  starts_at,
  ends_at,
  COALESCE(reason, '')::text AS reason,
  COALESCE(created_by, '')::text AS created_by,
  created_at
FROM alert_maintenance_windows
ORDER BY ends_at DESC
`

type ListMaintenanceWindowsRow struct {
	ID        string           `json:"id"`
	ScopeType string           `json:"scope_type"`
	ScopeID   string           `json:"scope_id"`
	StartsAt  pgtype.Timestamp `json:"starts_at"`
	EndsAt    pgtype.Timestamp `json:"ends_at"`
	Reason    string           `json:"reason"`
	CreatedBy string           `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListMaintenanceWindows(ctx context.Context) ([]ListMaintenanceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceWindowsRow{}
	for rows.Next() {
		var i ListMaintenanceWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMaintenanceWindow = `-- name: UpsertMaintenanceWindow :exec
INSERT INTO alert_maintenance_windows (
  id,
  scope_type,
  scope_id,
  starts_at,
  ends_at,
  reason,
  created_by,
  created_at
)
VALUES ($1, $2, $8, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
  scope_type = EXCLUDED.scope_type,
  scope_id = EXCLUDED.scope_id,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  reason = EXCLUDED.reason,
  created_by = EXCLUDED.created_by
`

type UpsertMaintenanceWindowParams struct {
	ID        string           `json:"id"`
	ScopeType string           `json:"scope_type"`
	StartsAt  pgtype.Timestamp `json:"starts_at"`
	EndsAt    pgtype.Timestamp `json:"ends_at"`
	Reason    pgtype.Text      `json:"reason"`
	CreatedBy pgtype.Text      `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ScopeID   pgtype.Text      `json:"scope_id"`
}

func (q *Queries) UpsertMaintenanceWindow(ctx context.Context, arg UpsertMaintenanceWindowParams) error {
	_, err := q.db.Exec(ctx, upsertMaintenanceWindow,
		arg.ID,
		arg.ScopeType,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ScopeID,
	)
	return err
}
