// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationRunLatencyPercentiles = `-- name: GetApplicationRunLatencyPercentiles :one
SELECT
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY r.duration_ms), 0)::int AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY r.duration_ms), 0)::int AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY r.duration_ms), 0)::int AS p99_ms,
  COALESCE(AVG(r.duration_ms), 0)::int AS avg_ms
FROM monitor_runs r
INNER JOIN monitors m ON m.id = r.monitor_id
WHERE m.application_id = $1
  AND r.started_at >= $2
  AND COALESCE(r.triggered_by, '') NOT IN ('draft', 'test')
  AND r.duration_ms IS NOT NULL
`

type GetApplicationRunLatencyPercentilesParams struct {
	ApplicationID pgtype.Text      `json:"application_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
}

type GetApplicationRunLatencyPercentilesRow struct {
	P50Ms int32 `json:"p50_ms"`
	P95Ms int32 `json:"p95_ms"`
	P99Ms int32 `json:"p99_ms"`
	AvgMs int32 `json:"avg_ms"`
}

func (q *Queries) GetApplicationRunLatencyPercentiles(ctx context.Context, arg GetApplicationRunLatencyPercentilesParams) (GetApplicationRunLatencyPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getApplicationRunLatencyPercentiles, arg.ApplicationID, arg.StartedAt)
	var i GetApplicationRunLatencyPercentilesRow
	err := row.Scan(
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
		&i.AvgMs,
	)
	return i, err
}

const getApplicationRunUptimeStats = `-- name: GetApplicationRunUptimeStats :one
SELECT
  COUNT(*)::bigint AS total_runs,
  COUNT(*) FILTER (WHERE UPPER(COALESCE(r.status, '')) = 'SUCCESS')::bigint AS successful_runs
FROM monitor_runs r
INNER JOIN monitors m ON m.id = r.monitor_id
WHERE m.application_id = $1
  AND r.started_at >= $2
  AND COALESCE(r.triggered_by, '') NOT IN ('draft', 'test')
`

type GetApplicationRunUptimeStatsParams struct {
	ApplicationID pgtype.Text      `json:"application_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
}

type GetApplicationRunUptimeStatsRow struct {
	TotalRuns      int64 `json:"total_runs"`
	SuccessfulRuns int64 `json:"successful_runs"`
}

func (q *Queries) GetApplicationRunUptimeStats(ctx context.Context, arg GetApplicationRunUptimeStatsParams) (GetApplicationRunUptimeStatsRow, error) {
	row := q.db.QueryRow(ctx, getApplicationRunUptimeStats, arg.ApplicationID, arg.StartedAt)
	var i GetApplicationRunUptimeStatsRow
	err := row.Scan(&i.TotalRuns, &i.SuccessfulRuns)
	return i, err
}

const getGlobalRunLatencyPercentiles = `-- name: GetGlobalRunLatencyPercentiles :one
SELECT
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p99_ms,
  COALESCE(AVG(duration_ms), 0)::int AS avg_ms
FROM monitor_runs
WHERE started_at >= $1
  AND COALESCE(triggered_by, '') NOT IN ('draft', 'test')
  AND duration_ms IS NOT NULL
`

type GetGlobalRunLatencyPercentilesRow struct {
	P50Ms int32 `json:"p50_ms"`
	P95Ms int32 `json:"p95_ms"`
	P99Ms int32 `json:"p99_ms"`
	AvgMs int32 `json:"avg_ms"`
}

func (q *Queries) GetGlobalRunLatencyPercentiles(ctx context.Context, startedAt pgtype.Timestamp) (GetGlobalRunLatencyPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getGlobalRunLatencyPercentiles, startedAt)
	var i GetGlobalRunLatencyPercentilesRow
	err := row.Scan(
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
		&i.AvgMs,
	)
	return i, err
}

const getGlobalRunUptimeStats = `-- name: GetGlobalRunUptimeStats :one
SELECT
  COUNT(*)::bigint AS total_runs,
  COUNT(*) FILTER (WHERE UPPER(COALESCE(status, '')) = 'SUCCESS')::bigint AS successful_runs
FROM monitor_runs
WHERE started_at >= $1
  AND COALESCE(triggered_by, '') NOT IN ('draft', 'test')
`

type GetGlobalRunUptimeStatsRow struct {
	TotalRuns      int64 `json:"total_runs"`
	SuccessfulRuns int64 `json:"successful_runs"`
}

func (q *Queries) GetGlobalRunUptimeStats(ctx context.Context, startedAt pgtype.Timestamp) (GetGlobalRunUptimeStatsRow, error) {
	row := q.db.QueryRow(ctx, getGlobalRunUptimeStats, startedAt)
	var i GetGlobalRunUptimeStatsRow
	err := row.Scan(&i.TotalRuns, &i.SuccessfulRuns)
	return i, err
}

const getMonitorRunLatencyPercentiles = `-- name: GetMonitorRunLatencyPercentiles :one
SELECT
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY duration_ms), 0)::int AS p99_ms,
  COALESCE(AVG(duration_ms), 0)::int AS avg_ms
FROM monitor_runs
WHERE monitor_id = $1
  AND started_at >= $2
  AND COALESCE(triggered_by, '') NOT IN ('draft', 'test')
  AND duration_ms IS NOT NULL
`

type GetMonitorRunLatencyPercentilesParams struct {
	MonitorID pgtype.Text      `json:"monitor_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}

type GetMonitorRunLatencyPercentilesRow struct {
	P50Ms int32 `json:"p50_ms"`
	P95Ms int32 `json:"p95_ms"`
	P99Ms int32 `json:"p99_ms"`
	AvgMs int32 `json:"avg_ms"`
}

func (q *Queries) GetMonitorRunLatencyPercentiles(ctx context.Context, arg GetMonitorRunLatencyPercentilesParams) (GetMonitorRunLatencyPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getMonitorRunLatencyPercentiles, arg.MonitorID, arg.StartedAt)
	var i GetMonitorRunLatencyPercentilesRow
	err := row.Scan(
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
		&i.AvgMs,
	)
	return i, err
}

const getMonitorRunUptimeStats = `-- name: GetMonitorRunUptimeStats :one
SELECT
  COUNT(*)::bigint AS total_runs,
  COUNT(*) FILTER (WHERE UPPER(COALESCE(status, '')) = 'SUCCESS')::bigint AS successful_runs
FROM monitor_runs
WHERE monitor_id = $1
  AND started_at >= $2
  AND COALESCE(triggered_by, '') NOT IN ('draft', 'test')
`

type GetMonitorRunUptimeStatsParams struct {
	MonitorID pgtype.Text      `json:"monitor_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}

type GetMonitorRunUptimeStatsRow struct {
	TotalRuns      int64 `json:"total_runs"`
	SuccessfulRuns int64 `json:"successful_runs"`
}

func (q *Queries) GetMonitorRunUptimeStats(ctx context.Context, arg GetMonitorRunUptimeStatsParams) (GetMonitorRunUptimeStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorRunUptimeStats, arg.MonitorID, arg.StartedAt)
	var i GetMonitorRunUptimeStatsRow
	err := row.Scan(&i.TotalRuns, &i.SuccessfulRuns)
	return i, err
}

const getMonitorStepLatencyPercentiles = `-- name: GetMonitorStepLatencyPercentiles :one
SELECT
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY sr.latency_ms), 0)::int AS p50_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY sr.latency_ms), 0)::int AS p95_ms,
  COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY sr.latency_ms), 0)::int AS p99_ms,
  COALESCE(AVG(sr.latency_ms), 0)::int AS avg_ms
FROM monitor_step_runs sr
INNER JOIN monitor_runs r ON r.id = sr.monitor_run_id
WHERE r.monitor_id = $1
  AND r.started_at >= $2
  AND COALESCE(r.triggered_by, '') NOT IN ('draft', 'test')
  AND sr.latency_ms IS NOT NULL
`

type GetMonitorStepLatencyPercentilesParams struct {
	MonitorID pgtype.Text      `json:"monitor_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}

type GetMonitorStepLatencyPercentilesRow struct {
	P50Ms int32 `json:"p50_ms"`
	P95Ms int32 `json:"p95_ms"`
	P99Ms int32 `json:"p99_ms"`
	AvgMs int32 `json:"avg_ms"`
}

func (q *Queries) GetMonitorStepLatencyPercentiles(ctx context.Context, arg GetMonitorStepLatencyPercentilesParams) (GetMonitorStepLatencyPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getMonitorStepLatencyPercentiles, arg.MonitorID, arg.StartedAt)
	var i GetMonitorStepLatencyPercentilesRow
	err := row.Scan(
		&i.P50Ms,
		&i.P95Ms,
		&i.P99Ms,
		&i.AvgMs,
	)
	return i, err
}
