// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	RunID             pgtype.Text      `json:"run_id"`
	Status            pgtype.Text      `json:"status"`
	Severity          pgtype.Text      `json:"severity"`
	Title             pgtype.Text      `json:"title"`
	Description       pgtype.Text      `json:"description"`
	FailureCategory   pgtype.Text      `json:"failure_category"`
	ChannelsJson      []byte           `json:"channels_json"`
	DeliveriesJson    []byte           `json:"deliveries_json"`
	FirstTriggeredAt  pgtype.Timestamp `json:"first_triggered_at"`
	LastTriggeredAt   pgtype.Timestamp `json:"last_triggered_at"`
	LastDeliveredAt   pgtype.Timestamp `json:"last_delivered_at"`
	ResolvedAt        pgtype.Timestamp `json:"resolved_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	AcknowledgedBy    pgtype.Text      `json:"acknowledged_by"`
	AcknowledgedAt    pgtype.Timestamp `json:"acknowledged_at"`
	SnoozedUntil      pgtype.Timestamp `json:"snoozed_until"`
	SuppressionReason pgtype.Text      `json:"suppression_reason"`
}

type AlertMaintenanceWindow struct {
	ID        string           `json:"id"`
	ScopeType string           `json:"scope_type"`
	ScopeID   pgtype.Text      `json:"scope_id"`
	StartsAt  pgtype.Timestamp `json:"starts_at"`
	EndsAt    pgtype.Timestamp `json:"ends_at"`
	Reason    pgtype.Text      `json:"reason"`
	CreatedBy pgtype.Text      `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Application struct {
	ID                  string           `json:"id"`
	Name                string           `json:"name"`
	CarID               string           `json:"car_id"`
	Description         pgtype.Text      `json:"description"`
	Owner               pgtype.Text      `json:"owner"`
	Environment         pgtype.Text      `json:"environment"`
	TagsJson            []byte           `json:"tags_json"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	AlertRoutingJson    []byte           `json:"alert_routing_json"`
	ElfAppID            pgtype.Text      `json:"elf_app_id"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	IndexPathTemplate   pgtype.Text      `json:"index_path_template"`
}

type ApplicationService struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	LogServiceName      string           `json:"log_service_name"`
	Squad               pgtype.Text      `json:"squad"`
	Owner               pgtype.Text      `json:"owner"`
	Environment         pgtype.Text      `json:"environment"`
	ElfAppID            pgtype.Text      `json:"elf_app_id"`
	LogFieldMappingJson []byte           `json:"log_field_mapping_json"`
	IsActive            bool             `json:"is_active"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	IndexPathTemplate   pgtype.Text      `json:"index_path_template"`
}

type CertificateProfile struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	Host                  string           `json:"host"`
	Port                  int32            `json:"port"`
	CertType              string           `json:"cert_type"`
	CertSecretAlias       pgtype.Text      `json:"cert_secret_alias"`
	KeySecretAlias        pgtype.Text      `json:"key_secret_alias"`
	PfxSecretAlias        pgtype.Text      `json:"pfx_secret_alias"`
	CaCertSecretAlias     pgtype.Text      `json:"ca_cert_secret_alias"`
	PassphraseSecretAlias pgtype.Text      `json:"passphrase_secret_alias"`
	InsecureSkipVerify    pgtype.Bool      `json:"insecure_skip_verify"`
	IsActive              pgtype.Bool      `json:"is_active"`
	LastTestedAt          pgtype.Timestamp `json:"last_tested_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type DeploymentValidation struct {
	ID                   string           `json:"id"`
	ApplicationID        pgtype.Text      `json:"application_id"`
	ApplicationName      string           `json:"application_name"`
	CarID                string           `json:"car_id"`
	Name                 string           `json:"name"`
	Version              pgtype.Text      `json:"version"`
	BuildID              pgtype.Text      `json:"build_id"`
	Environment          pgtype.Text      `json:"environment"`
	Status               string           `json:"status"`
	MonitorIdsJson       []byte           `json:"monitor_ids_json"`
	ReportJson           []byte           `json:"report_json"`
	PreStartedAt         pgtype.Timestamp `json:"pre_started_at"`
	PreCompletedAt       pgtype.Timestamp `json:"pre_completed_at"`
	PostStartedAt        pgtype.Timestamp `json:"post_started_at"`
	PostCompletedAt      pgtype.Timestamp `json:"post_completed_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	SampleCount          int32            `json:"sample_count"`
	IntervalSeconds      int32            `json:"interval_seconds"`
	AiReportJson         []byte           `json:"ai_report_json"`
	DeploymentStartedAt  pgtype.Timestamp `json:"deployment_started_at"`
	BaselineWindowHours  int32            `json:"baseline_window_hours"`
	BaselineRunCount     int32            `json:"baseline_run_count"`
	ElfQueryIdsJson      []byte           `json:"elf_query_ids_json"`
	AutoRunLogCheck      bool             `json:"auto_run_log_check"`
	ElfResultsJson       []byte           `json:"elf_results_json"`
	LogStartedAt         pgtype.Timestamp `json:"log_started_at"`
	LogCompletedAt       pgtype.Timestamp `json:"log_completed_at"`
	ServiceIdsJson       []byte           `json:"service_ids_json"`
	ObservabilityProfile string           `json:"observability_profile"`
	SignalPackIdsJson    []byte           `json:"signal_pack_ids_json"`
}

type DeploymentValidationRun struct {
	ValidationID string           `json:"validation_id"`
	Phase        string           `json:"phase"`
	MonitorID    string           `json:"monitor_id"`
	RunID        string           `json:"run_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type ElfQuery struct {
	ID                   string           `json:"id"`
	Name                 string           `json:"name"`
	Description          pgtype.Text      `json:"description"`
	ElfAppID             pgtype.Text      `json:"elf_app_id"`
	IndexPathTemplate    pgtype.Text      `json:"index_path_template"`
	SearchBodyJson       []byte           `json:"search_body_json"`
	GateMode             string           `json:"gate_mode"`
	PassCriteriaJson     []byte           `json:"pass_criteria_json"`
	ApplicationID        pgtype.Text      `json:"application_id"`
	TagsJson             []byte           `json:"tags_json"`
	IsActive             bool             `json:"is_active"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	SignalType           string           `json:"signal_type"`
	ComparisonConfigJson []byte           `json:"comparison_config_json"`
	ServiceID            pgtype.Text      `json:"service_id"`
}

type Monitor struct {
	ID                  string           `json:"id"`
	ApplicationID       pgtype.Text      `json:"application_id"`
	Name                string           `json:"name"`
	Description         pgtype.Text      `json:"description"`
	ScheduleMode        pgtype.Text      `json:"schedule_mode"`
	ScheduleLabel       pgtype.Text      `json:"schedule_label"`
	ScheduleCron        pgtype.Text      `json:"schedule_cron"`
	Timezone            pgtype.Text      `json:"timezone"`
	TimeoutMs           pgtype.Int4      `json:"timeout_ms"`
	RetryCount          pgtype.Int4      `json:"retry_count"`
	FailureThreshold    pgtype.Int4      `json:"failure_threshold"`
	ResponseBodyLimitKb pgtype.Int4      `json:"response_body_limit_kb"`
	IsActive            pgtype.Bool      `json:"is_active"`
	AlertEnabled        pgtype.Bool      `json:"alert_enabled"`
	VariablesJson       []byte           `json:"variables_json"`
	AlertPolicyJson     []byte           `json:"alert_policy_json"`
	Status              pgtype.Text      `json:"status"`
	LastRunAt           pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs      pgtype.Int4      `json:"last_duration_ms"`
	SuccessRate24h      pgtype.Numeric   `json:"success_rate_24h"`
	CreatedBy           pgtype.Text      `json:"created_by"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	PublishedVersion    int32            `json:"published_version"`
	HasUnpublishedDraft bool             `json:"has_unpublished_draft"`
	ServiceID           pgtype.Text      `json:"service_id"`
}

type MonitorDraft struct {
	MonitorID  string           `json:"monitor_id"`
	ConfigJson []byte           `json:"config_json"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type MonitorRun struct {
	ID              string           `json:"id"`
	MonitorID       pgtype.Text      `json:"monitor_id"`
	Status          pgtype.Text      `json:"status"`
	FailureCategory pgtype.Text      `json:"failure_category"`
	FailureReason   pgtype.Text      `json:"failure_reason"`
	TriggeredBy     pgtype.Text      `json:"triggered_by"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	DurationMs      pgtype.Int4      `json:"duration_ms"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type MonitorSecretBinding struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	SecretReferenceID pgtype.Text      `json:"secret_reference_id"`
	Alias             string           `json:"alias"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type MonitorStep struct {
	ID                string           `json:"id"`
	MonitorID         pgtype.Text      `json:"monitor_id"`
	StepOrder         int32            `json:"step_order"`
	Name              string           `json:"name"`
	StepType          string           `json:"step_type"`
	ConfigJson        []byte           `json:"config_json"`
	ActionsJson       []byte           `json:"actions_json"`
	AssertionsJson    []byte           `json:"assertions_json"`
	ExtractorsJson    []byte           `json:"extractors_json"`
	TimeoutMs         pgtype.Int4      `json:"timeout_ms"`
	RetryCount        pgtype.Int4      `json:"retry_count"`
	ContinueOnFailure pgtype.Bool      `json:"continue_on_failure"`
	IsActive          pgtype.Bool      `json:"is_active"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type MonitorStepRun struct {
	ID                   string           `json:"id"`
	MonitorRunID         pgtype.Text      `json:"monitor_run_id"`
	StepID               pgtype.Text      `json:"step_id"`
	StepOrder            pgtype.Int4      `json:"step_order"`
	StepName             pgtype.Text      `json:"step_name"`
	StepType             pgtype.Text      `json:"step_type"`
	Status               pgtype.Text      `json:"status"`
	RequestSummaryJson   []byte           `json:"request_summary_json"`
	ResponseSummaryJson  []byte           `json:"response_summary_json"`
	AssertionResultsJson []byte           `json:"assertion_results_json"`
	ExtractorResultsJson []byte           `json:"extractor_results_json"`
	ConsoleOutputJson    []byte           `json:"console_output_json"`
	TimingJson           []byte           `json:"timing_json"`
	LatencyMs            pgtype.Int4      `json:"latency_ms"`
	ErrorMessage         pgtype.Text      `json:"error_message"`
	StartedAt            pgtype.Timestamp `json:"started_at"`
	EndedAt              pgtype.Timestamp `json:"ended_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type MonitorVersion struct {
	ID            string           `json:"id"`
	MonitorID     string           `json:"monitor_id"`
	VersionNumber int32            `json:"version_number"`
	ConfigJson    []byte           `json:"config_json"`
	ChangeNote    pgtype.Text      `json:"change_note"`
	CreatedBy     pgtype.Text      `json:"created_by"`
	Source        string           `json:"source"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type SecretReference struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	Alias          string           `json:"alias"`
	Description    pgtype.Text      `json:"description"`
	Provider       string           `json:"provider"`
	SecretPath     pgtype.Text      `json:"secret_path"`
	SecretKey      pgtype.Text      `json:"secret_key"`
	EncryptedValue pgtype.Text      `json:"encrypted_value"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type SystemSetting struct {
	Key       string           `json:"key"`
	ValueJson []byte           `json:"value_json"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
