// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpPublishedVersion = `-- name: BumpPublishedVersion :exec
UPDATE monitors
SET
  published_version = $2,
  has_unpublished_draft = FALSE,
  updated_at = NOW()
WHERE id = $1
`

type BumpPublishedVersionParams struct {
	ID               string `json:"id"`
	PublishedVersion int32  `json:"published_version"`
}

func (q *Queries) BumpPublishedVersion(ctx context.Context, arg BumpPublishedVersionParams) error {
	_, err := q.db.Exec(ctx, bumpPublishedVersion, arg.ID, arg.PublishedVersion)
	return err
}

const deleteMonitorDraft = `-- name: DeleteMonitorDraft :exec
DELETE FROM monitor_drafts
WHERE monitor_id = $1
`

func (q *Queries) DeleteMonitorDraft(ctx context.Context, monitorID string) error {
	_, err := q.db.Exec(ctx, deleteMonitorDraft, monitorID)
	return err
}

const deleteMonitorVersions = `-- name: DeleteMonitorVersions :exec
DELETE FROM monitor_versions
WHERE monitor_id = $1
`

func (q *Queries) DeleteMonitorVersions(ctx context.Context, monitorID string) error {
	_, err := q.db.Exec(ctx, deleteMonitorVersions, monitorID)
	return err
}

const getMaxMonitorVersion = `-- name: GetMaxMonitorVersion :one
SELECT COALESCE(MAX(version_number), 0)::int AS max_version
FROM monitor_versions
WHERE monitor_id = $1
`

func (q *Queries) GetMaxMonitorVersion(ctx context.Context, monitorID string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxMonitorVersion, monitorID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getMonitorDraft = `-- name: GetMonitorDraft :one
SELECT config_json, updated_at
FROM monitor_drafts
WHERE monitor_id = $1
`

type GetMonitorDraftRow struct {
	ConfigJson []byte           `json:"config_json"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetMonitorDraft(ctx context.Context, monitorID string) (GetMonitorDraftRow, error) {
	row := q.db.QueryRow(ctx, getMonitorDraft, monitorID)
	var i GetMonitorDraftRow
	err := row.Scan(&i.ConfigJson, &i.UpdatedAt)
	return i, err
}

const getMonitorVersion = `-- name: GetMonitorVersion :one
SELECT
  id,
  monitor_id,
  version_number,
  config_json,
  change_note,
  COALESCE(created_by, '')::text AS created_by,
  source,
  created_at
FROM monitor_versions
WHERE monitor_id = $1 AND version_number = $2
`

type GetMonitorVersionParams struct {
	MonitorID     string `json:"monitor_id"`
	VersionNumber int32  `json:"version_number"`
}

type GetMonitorVersionRow struct {
	ID            string           `json:"id"`
	MonitorID     string           `json:"monitor_id"`
	VersionNumber int32            `json:"version_number"`
	ConfigJson    []byte           `json:"config_json"`
	ChangeNote    pgtype.Text      `json:"change_note"`
	CreatedBy     string           `json:"created_by"`
	Source        string           `json:"source"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMonitorVersion(ctx context.Context, arg GetMonitorVersionParams) (GetMonitorVersionRow, error) {
	row := q.db.QueryRow(ctx, getMonitorVersion, arg.MonitorID, arg.VersionNumber)
	var i GetMonitorVersionRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.VersionNumber,
		&i.ConfigJson,
		&i.ChangeNote,
		&i.CreatedBy,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertMonitorVersion = `-- name: InsertMonitorVersion :exec
INSERT INTO monitor_versions (
  id,
  monitor_id,
  version_number,
  config_json,
  change_note,
  created_by,
  source,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMonitorVersionParams struct {
	ID            string           `json:"id"`
	MonitorID     string           `json:"monitor_id"`
	VersionNumber int32            `json:"version_number"`
	ConfigJson    []byte           `json:"config_json"`
	ChangeNote    pgtype.Text      `json:"change_note"`
	CreatedBy     pgtype.Text      `json:"created_by"`
	Source        string           `json:"source"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) InsertMonitorVersion(ctx context.Context, arg InsertMonitorVersionParams) error {
	_, err := q.db.Exec(ctx, insertMonitorVersion,
		arg.ID,
		arg.MonitorID,
		arg.VersionNumber,
		arg.ConfigJson,
		arg.ChangeNote,
		arg.CreatedBy,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const listMonitorVersions = `-- name: ListMonitorVersions :many
SELECT
  id,
  monitor_id,
  version_number,
  change_note,
  COALESCE(created_by, '')::text AS created_by,
  source,
  created_at
FROM monitor_versions
WHERE monitor_id = $1
ORDER BY version_number DESC
`

type ListMonitorVersionsRow struct {
	ID            string           `json:"id"`
	MonitorID     string           `json:"monitor_id"`
	VersionNumber int32            `json:"version_number"`
	ChangeNote    pgtype.Text      `json:"change_note"`
	CreatedBy     string           `json:"created_by"`
	Source        string           `json:"source"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListMonitorVersions(ctx context.Context, monitorID string) ([]ListMonitorVersionsRow, error) {
	rows, err := q.db.Query(ctx, listMonitorVersions, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorVersionsRow{}
	for rows.Next() {
		var i ListMonitorVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.VersionNumber,
			&i.ChangeNote,
			&i.CreatedBy,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMonitorDraftFlags = `-- name: SetMonitorDraftFlags :exec
UPDATE monitors
SET
  has_unpublished_draft = $2,
  updated_at = NOW()
WHERE id = $1
`

type SetMonitorDraftFlagsParams struct {
	ID                  string `json:"id"`
	HasUnpublishedDraft bool   `json:"has_unpublished_draft"`
}

func (q *Queries) SetMonitorDraftFlags(ctx context.Context, arg SetMonitorDraftFlagsParams) error {
	_, err := q.db.Exec(ctx, setMonitorDraftFlags, arg.ID, arg.HasUnpublishedDraft)
	return err
}

const upsertMonitorDraft = `-- name: UpsertMonitorDraft :exec
INSERT INTO monitor_drafts (monitor_id, config_json, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (monitor_id) DO UPDATE SET
  config_json = EXCLUDED.config_json,
  updated_at = NOW()
`

type UpsertMonitorDraftParams struct {
	MonitorID  string `json:"monitor_id"`
	ConfigJson []byte `json:"config_json"`
}

func (q *Queries) UpsertMonitorDraft(ctx context.Context, arg UpsertMonitorDraftParams) error {
	_, err := q.db.Exec(ctx, upsertMonitorDraft, arg.MonitorID, arg.ConfigJson)
	return err
}
