// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMonitors = `-- name: CountMonitors :one
SELECT COUNT(*)::int
FROM monitors
`

func (q *Queries) CountMonitors(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countMonitors)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMonitorSecretBindings = `-- name: DeleteMonitorSecretBindings :exec
DELETE FROM monitor_secret_bindings
WHERE monitor_id = $1
`

func (q *Queries) DeleteMonitorSecretBindings(ctx context.Context, monitorID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteMonitorSecretBindings, monitorID)
	return err
}

const deleteMonitorSteps = `-- name: DeleteMonitorSteps :exec
DELETE FROM monitor_steps
WHERE monitor_id = $1
`

func (q *Queries) DeleteMonitorSteps(ctx context.Context, monitorID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteMonitorSteps, monitorID)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT
  id,
  COALESCE(application_id, '')::text AS application_id,
  name,
  COALESCE(description, '')::text AS description,
  COALESCE(schedule_mode, '')::text AS schedule_mode,
  COALESCE(schedule_label, '')::text AS schedule_label,
  COALESCE(schedule_cron, '')::text AS schedule_cron,
  COALESCE(timezone, 'UTC')::text AS timezone,
  COALESCE(timeout_ms, 30000)::int AS timeout_ms,
  COALESCE(retry_count, 0)::int AS retry_count,
  COALESCE(failure_threshold, 3)::int AS failure_threshold,
  COALESCE(response_body_limit_kb, 32)::int AS response_body_limit_kb,
  COALESCE(is_active, TRUE)::bool AS is_active,
  COALESCE(alert_enabled, FALSE)::bool AS alert_enabled,
  variables_json,
  alert_policy_json,
  COALESCE(status, '')::text AS status,
  last_run_at,
  COALESCE(last_duration_ms, 0)::int AS last_duration_ms,
  COALESCE(success_rate_24h, 0)::float8 AS success_rate_24h,
  COALESCE(published_version, 1)::int AS published_version,
  COALESCE(has_unpublished_draft, FALSE)::bool AS has_unpublished_draft,
  created_at,
  updated_at
FROM monitors
WHERE id = $1
`

type GetMonitorRow struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	Description         string           `json:"description"`
	ScheduleMode        string           `json:"schedule_mode"`
	ScheduleLabel       string           `json:"schedule_label"`
	ScheduleCron        string           `json:"schedule_cron"`
	Timezone            string           `json:"timezone"`
	TimeoutMs           int32            `json:"timeout_ms"`
	RetryCount          int32            `json:"retry_count"`
	FailureThreshold    int32            `json:"failure_threshold"`
	ResponseBodyLimitKb int32            `json:"response_body_limit_kb"`
	IsActive            bool             `json:"is_active"`
	AlertEnabled        bool             `json:"alert_enabled"`
	VariablesJson       []byte           `json:"variables_json"`
	AlertPolicyJson     []byte           `json:"alert_policy_json"`
	Status              string           `json:"status"`
	LastRunAt           pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs      int32            `json:"last_duration_ms"`
	SuccessRate24h      float64          `json:"success_rate_24h"`
	PublishedVersion    int32            `json:"published_version"`
	HasUnpublishedDraft bool             `json:"has_unpublished_draft"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetMonitor(ctx context.Context, id string) (GetMonitorRow, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i GetMonitorRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Description,
		&i.ScheduleMode,
		&i.ScheduleLabel,
		&i.ScheduleCron,
		&i.Timezone,
		&i.TimeoutMs,
		&i.RetryCount,
		&i.FailureThreshold,
		&i.ResponseBodyLimitKb,
		&i.IsActive,
		&i.AlertEnabled,
		&i.VariablesJson,
		&i.AlertPolicyJson,
		&i.Status,
		&i.LastRunAt,
		&i.LastDurationMs,
		&i.SuccessRate24h,
		&i.PublishedVersion,
		&i.HasUnpublishedDraft,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretIDForAlias = `-- name: GetSecretIDForAlias :one
SELECT id
FROM secret_references
WHERE alias = $1
`

func (q *Queries) GetSecretIDForAlias(ctx context.Context, alias string) (string, error) {
	row := q.db.QueryRow(ctx, getSecretIDForAlias, alias)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getStepMonitorID = `-- name: GetStepMonitorID :one
SELECT monitor_id
FROM monitor_steps
WHERE id = $1
`

func (q *Queries) GetStepMonitorID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getStepMonitorID, id)
	var monitor_id pgtype.Text
	err := row.Scan(&monitor_id)
	return monitor_id, err
}

const insertMonitorStep = `-- name: InsertMonitorStep :exec
INSERT INTO monitor_steps (
  id,
  monitor_id,
  step_order,
  name,
  step_type,
  config_json,
  actions_json,
  assertions_json,
  extractors_json,
  timeout_ms,
  retry_count,
  continue_on_failure,
  updated_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW())
`

type InsertMonitorStepParams struct {
	ID                string      `json:"id"`
	MonitorID         pgtype.Text `json:"monitor_id"`
	StepOrder         int32       `json:"step_order"`
	Name              string      `json:"name"`
	StepType          string      `json:"step_type"`
	ConfigJson        []byte      `json:"config_json"`
	ActionsJson       []byte      `json:"actions_json"`
	AssertionsJson    []byte      `json:"assertions_json"`
	ExtractorsJson    []byte      `json:"extractors_json"`
	TimeoutMs         pgtype.Int4 `json:"timeout_ms"`
	RetryCount        pgtype.Int4 `json:"retry_count"`
	ContinueOnFailure pgtype.Bool `json:"continue_on_failure"`
}

func (q *Queries) InsertMonitorStep(ctx context.Context, arg InsertMonitorStepParams) error {
	_, err := q.db.Exec(ctx, insertMonitorStep,
		arg.ID,
		arg.MonitorID,
		arg.StepOrder,
		arg.Name,
		arg.StepType,
		arg.ConfigJson,
		arg.ActionsJson,
		arg.AssertionsJson,
		arg.ExtractorsJson,
		arg.TimeoutMs,
		arg.RetryCount,
		arg.ContinueOnFailure,
	)
	return err
}

const listMonitors = `-- name: ListMonitors :many
SELECT
  id,
  COALESCE(application_id, '')::text AS application_id,
  name,
  COALESCE(description, '')::text AS description,
  COALESCE(schedule_mode, '')::text AS schedule_mode,
  COALESCE(schedule_label, '')::text AS schedule_label,
  COALESCE(schedule_cron, '')::text AS schedule_cron,
  COALESCE(timezone, 'UTC')::text AS timezone,
  COALESCE(timeout_ms, 30000)::int AS timeout_ms,
  COALESCE(retry_count, 0)::int AS retry_count,
  COALESCE(failure_threshold, 3)::int AS failure_threshold,
  COALESCE(response_body_limit_kb, 32)::int AS response_body_limit_kb,
  COALESCE(is_active, TRUE)::bool AS is_active,
  COALESCE(alert_enabled, FALSE)::bool AS alert_enabled,
  variables_json,
  alert_policy_json,
  COALESCE(status, '')::text AS status,
  last_run_at,
  COALESCE(last_duration_ms, 0)::int AS last_duration_ms,
  COALESCE(success_rate_24h, 0)::float8 AS success_rate_24h,
  COALESCE(published_version, 1)::int AS published_version,
  COALESCE(has_unpublished_draft, FALSE)::bool AS has_unpublished_draft,
  created_at,
  updated_at
FROM monitors
ORDER BY created_at DESC
`

type ListMonitorsRow struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	Description         string           `json:"description"`
	ScheduleMode        string           `json:"schedule_mode"`
	ScheduleLabel       string           `json:"schedule_label"`
	ScheduleCron        string           `json:"schedule_cron"`
	Timezone            string           `json:"timezone"`
	TimeoutMs           int32            `json:"timeout_ms"`
	RetryCount          int32            `json:"retry_count"`
	FailureThreshold    int32            `json:"failure_threshold"`
	ResponseBodyLimitKb int32            `json:"response_body_limit_kb"`
	IsActive            bool             `json:"is_active"`
	AlertEnabled        bool             `json:"alert_enabled"`
	VariablesJson       []byte           `json:"variables_json"`
	AlertPolicyJson     []byte           `json:"alert_policy_json"`
	Status              string           `json:"status"`
	LastRunAt           pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs      int32            `json:"last_duration_ms"`
	SuccessRate24h      float64          `json:"success_rate_24h"`
	PublishedVersion    int32            `json:"published_version"`
	HasUnpublishedDraft bool             `json:"has_unpublished_draft"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListMonitors(ctx context.Context) ([]ListMonitorsRow, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorsRow{}
	for rows.Next() {
		var i ListMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Description,
			&i.ScheduleMode,
			&i.ScheduleLabel,
			&i.ScheduleCron,
			&i.Timezone,
			&i.TimeoutMs,
			&i.RetryCount,
			&i.FailureThreshold,
			&i.ResponseBodyLimitKb,
			&i.IsActive,
			&i.AlertEnabled,
			&i.VariablesJson,
			&i.AlertPolicyJson,
			&i.Status,
			&i.LastRunAt,
			&i.LastDurationMs,
			&i.SuccessRate24h,
			&i.PublishedVersion,
			&i.HasUnpublishedDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByApplication = `-- name: ListMonitorsByApplication :many
SELECT
  id,
  COALESCE(application_id, '')::text AS application_id,
  name,
  COALESCE(description, '')::text AS description,
  COALESCE(schedule_mode, '')::text AS schedule_mode,
  COALESCE(schedule_label, '')::text AS schedule_label,
  COALESCE(schedule_cron, '')::text AS schedule_cron,
  COALESCE(timezone, 'UTC')::text AS timezone,
  COALESCE(timeout_ms, 30000)::int AS timeout_ms,
  COALESCE(retry_count, 0)::int AS retry_count,
  COALESCE(failure_threshold, 3)::int AS failure_threshold,
  COALESCE(response_body_limit_kb, 32)::int AS response_body_limit_kb,
  COALESCE(is_active, TRUE)::bool AS is_active,
  COALESCE(alert_enabled, FALSE)::bool AS alert_enabled,
  variables_json,
  alert_policy_json,
  COALESCE(status, '')::text AS status,
  last_run_at,
  COALESCE(last_duration_ms, 0)::int AS last_duration_ms,
  COALESCE(success_rate_24h, 0)::float8 AS success_rate_24h,
  COALESCE(published_version, 1)::int AS published_version,
  COALESCE(has_unpublished_draft, FALSE)::bool AS has_unpublished_draft,
  created_at,
  updated_at
FROM monitors
WHERE application_id = $1
ORDER BY created_at DESC
`

type ListMonitorsByApplicationRow struct {
	ID                  string           `json:"id"`
	ApplicationID       string           `json:"application_id"`
	Name                string           `json:"name"`
	Description         string           `json:"description"`
	ScheduleMode        string           `json:"schedule_mode"`
	ScheduleLabel       string           `json:"schedule_label"`
	ScheduleCron        string           `json:"schedule_cron"`
	Timezone            string           `json:"timezone"`
	TimeoutMs           int32            `json:"timeout_ms"`
	RetryCount          int32            `json:"retry_count"`
	FailureThreshold    int32            `json:"failure_threshold"`
	ResponseBodyLimitKb int32            `json:"response_body_limit_kb"`
	IsActive            bool             `json:"is_active"`
	AlertEnabled        bool             `json:"alert_enabled"`
	VariablesJson       []byte           `json:"variables_json"`
	AlertPolicyJson     []byte           `json:"alert_policy_json"`
	Status              string           `json:"status"`
	LastRunAt           pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs      int32            `json:"last_duration_ms"`
	SuccessRate24h      float64          `json:"success_rate_24h"`
	PublishedVersion    int32            `json:"published_version"`
	HasUnpublishedDraft bool             `json:"has_unpublished_draft"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListMonitorsByApplication(ctx context.Context, applicationID pgtype.Text) ([]ListMonitorsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listMonitorsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonitorsByApplicationRow{}
	for rows.Next() {
		var i ListMonitorsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Description,
			&i.ScheduleMode,
			&i.ScheduleLabel,
			&i.ScheduleCron,
			&i.Timezone,
			&i.TimeoutMs,
			&i.RetryCount,
			&i.FailureThreshold,
			&i.ResponseBodyLimitKb,
			&i.IsActive,
			&i.AlertEnabled,
			&i.VariablesJson,
			&i.AlertPolicyJson,
			&i.Status,
			&i.LastRunAt,
			&i.LastDurationMs,
			&i.SuccessRate24h,
			&i.PublishedVersion,
			&i.HasUnpublishedDraft,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretAliases = `-- name: ListSecretAliases :many
SELECT alias
FROM monitor_secret_bindings
WHERE monitor_id = $1
ORDER BY created_at
`

func (q *Queries) ListSecretAliases(ctx context.Context, monitorID pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, listSecretAliases, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT
  id,
  monitor_id,
  step_order,
  name,
  step_type,
  config_json,
  actions_json,
  assertions_json,
  extractors_json,
  COALESCE(timeout_ms, 0)::int AS timeout_ms,
  COALESCE(retry_count, 0)::int AS retry_count,
  COALESCE(continue_on_failure, FALSE)::bool AS continue_on_failure
FROM monitor_steps
WHERE monitor_id = $1
ORDER BY step_order
`

type ListStepsRow struct {
	ID                string      `json:"id"`
	MonitorID         pgtype.Text `json:"monitor_id"`
	StepOrder         int32       `json:"step_order"`
	Name              string      `json:"name"`
	StepType          string      `json:"step_type"`
	ConfigJson        []byte      `json:"config_json"`
	ActionsJson       []byte      `json:"actions_json"`
	AssertionsJson    []byte      `json:"assertions_json"`
	ExtractorsJson    []byte      `json:"extractors_json"`
	TimeoutMs         int32       `json:"timeout_ms"`
	RetryCount        int32       `json:"retry_count"`
	ContinueOnFailure bool        `json:"continue_on_failure"`
}

func (q *Queries) ListSteps(ctx context.Context, monitorID pgtype.Text) ([]ListStepsRow, error) {
	rows, err := q.db.Query(ctx, listSteps, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepsRow{}
	for rows.Next() {
		var i ListStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StepOrder,
			&i.Name,
			&i.StepType,
			&i.ConfigJson,
			&i.ActionsJson,
			&i.AssertionsJson,
			&i.ExtractorsJson,
			&i.TimeoutMs,
			&i.RetryCount,
			&i.ContinueOnFailure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonitor = `-- name: UpsertMonitor :exec
INSERT INTO monitors (
  id,
  application_id,
  name,
  description,
  schedule_mode,
  schedule_label,
  schedule_cron,
  timezone,
  timeout_ms,
  retry_count,
  failure_threshold,
  response_body_limit_kb,
  is_active,
  alert_enabled,
  variables_json,
  alert_policy_json,
  status,
  last_run_at,
  last_duration_ms,
  success_rate_24h,
  created_at,
  updated_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
  $18, $19, $20, $21, $22
)
ON CONFLICT (id) DO UPDATE SET
  application_id = EXCLUDED.application_id,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  schedule_mode = EXCLUDED.schedule_mode,
  schedule_label = EXCLUDED.schedule_label,
  schedule_cron = EXCLUDED.schedule_cron,
  timezone = EXCLUDED.timezone,
  timeout_ms = EXCLUDED.timeout_ms,
  retry_count = EXCLUDED.retry_count,
  failure_threshold = EXCLUDED.failure_threshold,
  response_body_limit_kb = EXCLUDED.response_body_limit_kb,
  is_active = EXCLUDED.is_active,
  alert_enabled = EXCLUDED.alert_enabled,
  variables_json = EXCLUDED.variables_json,
  alert_policy_json = EXCLUDED.alert_policy_json,
  status = EXCLUDED.status,
  last_run_at = EXCLUDED.last_run_at,
  last_duration_ms = EXCLUDED.last_duration_ms,
  success_rate_24h = EXCLUDED.success_rate_24h,
  updated_at = EXCLUDED.updated_at
`

type UpsertMonitorParams struct {
	ID                  string           `json:"id"`
	ApplicationID       pgtype.Text      `json:"application_id"`
	Name                string           `json:"name"`
	Description         pgtype.Text      `json:"description"`
	ScheduleMode        pgtype.Text      `json:"schedule_mode"`
	ScheduleLabel       pgtype.Text      `json:"schedule_label"`
	ScheduleCron        pgtype.Text      `json:"schedule_cron"`
	Timezone            pgtype.Text      `json:"timezone"`
	TimeoutMs           pgtype.Int4      `json:"timeout_ms"`
	RetryCount          pgtype.Int4      `json:"retry_count"`
	FailureThreshold    pgtype.Int4      `json:"failure_threshold"`
	ResponseBodyLimitKb pgtype.Int4      `json:"response_body_limit_kb"`
	IsActive            pgtype.Bool      `json:"is_active"`
	AlertEnabled        pgtype.Bool      `json:"alert_enabled"`
	VariablesJson       []byte           `json:"variables_json"`
	AlertPolicyJson     []byte           `json:"alert_policy_json"`
	Status              pgtype.Text      `json:"status"`
	LastRunAt           pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs      pgtype.Int4      `json:"last_duration_ms"`
	SuccessRate24h      pgtype.Numeric   `json:"success_rate_24h"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertMonitor(ctx context.Context, arg UpsertMonitorParams) error {
	_, err := q.db.Exec(ctx, upsertMonitor,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.Description,
		arg.ScheduleMode,
		arg.ScheduleLabel,
		arg.ScheduleCron,
		arg.Timezone,
		arg.TimeoutMs,
		arg.RetryCount,
		arg.FailureThreshold,
		arg.ResponseBodyLimitKb,
		arg.IsActive,
		arg.AlertEnabled,
		arg.VariablesJson,
		arg.AlertPolicyJson,
		arg.Status,
		arg.LastRunAt,
		arg.LastDurationMs,
		arg.SuccessRate24h,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertMonitorSecretBinding = `-- name: UpsertMonitorSecretBinding :exec
INSERT INTO monitor_secret_bindings (id, monitor_id, secret_reference_id, alias)
VALUES ($1,$2,$3,$4)
ON CONFLICT (monitor_id, alias) DO UPDATE SET secret_reference_id = EXCLUDED.secret_reference_id
`

type UpsertMonitorSecretBindingParams struct {
	ID                string      `json:"id"`
	MonitorID         pgtype.Text `json:"monitor_id"`
	SecretReferenceID pgtype.Text `json:"secret_reference_id"`
	Alias             string      `json:"alias"`
}

func (q *Queries) UpsertMonitorSecretBinding(ctx context.Context, arg UpsertMonitorSecretBindingParams) error {
	_, err := q.db.Exec(ctx, upsertMonitorSecretBinding,
		arg.ID,
		arg.MonitorID,
		arg.SecretReferenceID,
		arg.Alias,
	)
	return err
}
