// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunsOlderThan = `-- name: CountRunsOlderThan :one
SELECT COUNT(*)::bigint AS count
FROM monitor_runs
WHERE started_at < $1
`

func (q *Queries) CountRunsOlderThan(ctx context.Context, startedAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsOlderThan, startedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRunsOlderThan = `-- name: DeleteRunsOlderThan :execrows
DELETE FROM monitor_runs
WHERE started_at < $1
`

func (q *Queries) DeleteRunsOlderThan(ctx context.Context, startedAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunsOlderThan, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT
  r.id,
  r.monitor_id,
  COALESCE(m.name, '')::text AS monitor_name,
  COALESCE(r.status, '')::text AS status,
  COALESCE(r.failure_category, '')::text AS failure_category,
  COALESCE(r.failure_reason, '')::text AS failure_reason,
  COALESCE(r.triggered_by, '')::text AS triggered_by,
  r.started_at,
  r.ended_at,
  COALESCE(r.duration_ms, 0)::int AS duration_ms
FROM monitor_runs r
LEFT JOIN monitors m ON m.id = r.monitor_id
WHERE r.id = $1
`

type GetRunRow struct {
	ID              string           `json:"id"`
	MonitorID       pgtype.Text      `json:"monitor_id"`
	MonitorName     string           `json:"monitor_name"`
	Status          string           `json:"status"`
	FailureCategory string           `json:"failure_category"`
	FailureReason   string           `json:"failure_reason"`
	TriggeredBy     string           `json:"triggered_by"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	DurationMs      int32            `json:"duration_ms"`
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.MonitorName,
		&i.Status,
		&i.FailureCategory,
		&i.FailureReason,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
	)
	return i, err
}

const insertMonitorRun = `-- name: InsertMonitorRun :exec
INSERT INTO monitor_runs (
  id,
  monitor_id,
  status,
  failure_category,
  failure_reason,
  triggered_by,
  started_at,
  ended_at,
  duration_ms
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (id) DO NOTHING
`

type InsertMonitorRunParams struct {
	ID              string           `json:"id"`
	MonitorID       pgtype.Text      `json:"monitor_id"`
	Status          pgtype.Text      `json:"status"`
	FailureCategory pgtype.Text      `json:"failure_category"`
	FailureReason   pgtype.Text      `json:"failure_reason"`
	TriggeredBy     pgtype.Text      `json:"triggered_by"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	DurationMs      pgtype.Int4      `json:"duration_ms"`
}

func (q *Queries) InsertMonitorRun(ctx context.Context, arg InsertMonitorRunParams) error {
	_, err := q.db.Exec(ctx, insertMonitorRun,
		arg.ID,
		arg.MonitorID,
		arg.Status,
		arg.FailureCategory,
		arg.FailureReason,
		arg.TriggeredBy,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMs,
	)
	return err
}

const insertMonitorStepRun = `-- name: InsertMonitorStepRun :exec
INSERT INTO monitor_step_runs (
  id,
  monitor_run_id,
  step_id,
  step_order,
  step_name,
  step_type,
  status,
  request_summary_json,
  response_summary_json,
  assertion_results_json,
  extractor_results_json,
  console_output_json,
  timing_json,
  latency_ms,
  error_message,
  started_at,
  ended_at
)
VALUES (
  $1,
  $2,
  $17,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
)
ON CONFLICT (id) DO NOTHING
`

type InsertMonitorStepRunParams struct {
	ID                   string           `json:"id"`
	MonitorRunID         pgtype.Text      `json:"monitor_run_id"`
	StepOrder            pgtype.Int4      `json:"step_order"`
	StepName             pgtype.Text      `json:"step_name"`
	StepType             pgtype.Text      `json:"step_type"`
	Status               pgtype.Text      `json:"status"`
	RequestSummaryJson   []byte           `json:"request_summary_json"`
	ResponseSummaryJson  []byte           `json:"response_summary_json"`
	AssertionResultsJson []byte           `json:"assertion_results_json"`
	ExtractorResultsJson []byte           `json:"extractor_results_json"`
	ConsoleOutputJson    []byte           `json:"console_output_json"`
	TimingJson           []byte           `json:"timing_json"`
	LatencyMs            pgtype.Int4      `json:"latency_ms"`
	ErrorMessage         pgtype.Text      `json:"error_message"`
	StartedAt            pgtype.Timestamp `json:"started_at"`
	EndedAt              pgtype.Timestamp `json:"ended_at"`
	StepID               pgtype.Text      `json:"step_id"`
}

func (q *Queries) InsertMonitorStepRun(ctx context.Context, arg InsertMonitorStepRunParams) error {
	_, err := q.db.Exec(ctx, insertMonitorStepRun,
		arg.ID,
		arg.MonitorRunID,
		arg.StepOrder,
		arg.StepName,
		arg.StepType,
		arg.Status,
		arg.RequestSummaryJson,
		arg.ResponseSummaryJson,
		arg.AssertionResultsJson,
		arg.ExtractorResultsJson,
		arg.ConsoleOutputJson,
		arg.TimingJson,
		arg.LatencyMs,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.EndedAt,
		arg.StepID,
	)
	return err
}

const listRuns = `-- name: ListRuns :many
SELECT
  r.id,
  r.monitor_id,
  COALESCE(m.name, '')::text AS monitor_name,
  COALESCE(r.status, '')::text AS status,
  COALESCE(r.failure_category, '')::text AS failure_category,
  COALESCE(r.failure_reason, '')::text AS failure_reason,
  COALESCE(r.triggered_by, '')::text AS triggered_by,
  r.started_at,
  r.ended_at,
  COALESCE(r.duration_ms, 0)::int AS duration_ms
FROM monitor_runs r
LEFT JOIN monitors m ON m.id = r.monitor_id
WHERE $1::text IS NULL OR r.monitor_id = $1
ORDER BY r.started_at DESC
`

type ListRunsRow struct {
	ID              string           `json:"id"`
	MonitorID       pgtype.Text      `json:"monitor_id"`
	MonitorName     string           `json:"monitor_name"`
	Status          string           `json:"status"`
	FailureCategory string           `json:"failure_category"`
	FailureReason   string           `json:"failure_reason"`
	TriggeredBy     string           `json:"triggered_by"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	EndedAt         pgtype.Timestamp `json:"ended_at"`
	DurationMs      int32            `json:"duration_ms"`
}

func (q *Queries) ListRuns(ctx context.Context, monitorID pgtype.Text) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.MonitorName,
			&i.Status,
			&i.FailureCategory,
			&i.FailureReason,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepRuns = `-- name: ListStepRuns :many
SELECT
  id,
  COALESCE(step_id, '')::text AS step_id,
  COALESCE(step_name, '')::text AS step_name,
  COALESCE(step_type, '')::text AS step_type,
  COALESCE(status, '')::text AS status,
  request_summary_json,
  response_summary_json,
  assertion_results_json,
  extractor_results_json,
  console_output_json,
  COALESCE(timing_json, '{}'::jsonb) AS timing_json,
  COALESCE(latency_ms, 0)::int AS latency_ms,
  COALESCE(error_message, '')::text AS error_message
FROM monitor_step_runs
WHERE monitor_run_id = $1
ORDER BY step_order
`

type ListStepRunsRow struct {
	ID                   string `json:"id"`
	StepID               string `json:"step_id"`
	StepName             string `json:"step_name"`
	StepType             string `json:"step_type"`
	Status               string `json:"status"`
	RequestSummaryJson   []byte `json:"request_summary_json"`
	ResponseSummaryJson  []byte `json:"response_summary_json"`
	AssertionResultsJson []byte `json:"assertion_results_json"`
	ExtractorResultsJson []byte `json:"extractor_results_json"`
	ConsoleOutputJson    []byte `json:"console_output_json"`
	TimingJson           []byte `json:"timing_json"`
	LatencyMs            int32  `json:"latency_ms"`
	ErrorMessage         string `json:"error_message"`
}

func (q *Queries) ListStepRuns(ctx context.Context, monitorRunID pgtype.Text) ([]ListStepRunsRow, error) {
	rows, err := q.db.Query(ctx, listStepRuns, monitorRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepRunsRow{}
	for rows.Next() {
		var i ListStepRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.StepName,
			&i.StepType,
			&i.Status,
			&i.RequestSummaryJson,
			&i.ResponseSummaryJson,
			&i.AssertionResultsJson,
			&i.ExtractorResultsJson,
			&i.ConsoleOutputJson,
			&i.TimingJson,
			&i.LatencyMs,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitorAfterRun = `-- name: UpdateMonitorAfterRun :exec
UPDATE monitors
SET status = $2, last_run_at = $3, last_duration_ms = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateMonitorAfterRunParams struct {
	ID             string           `json:"id"`
	Status         pgtype.Text      `json:"status"`
	LastRunAt      pgtype.Timestamp `json:"last_run_at"`
	LastDurationMs pgtype.Int4      `json:"last_duration_ms"`
}

func (q *Queries) UpdateMonitorAfterRun(ctx context.Context, arg UpdateMonitorAfterRunParams) error {
	_, err := q.db.Exec(ctx, updateMonitorAfterRun,
		arg.ID,
		arg.Status,
		arg.LastRunAt,
		arg.LastDurationMs,
	)
	return err
}
