// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEncryptedSecretByID = `-- name: GetEncryptedSecretByID :one
SELECT COALESCE(encrypted_value, '')::text AS encrypted_value
FROM secret_references
WHERE id = $1
`

func (q *Queries) GetEncryptedSecretByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEncryptedSecretByID, id)
	var encrypted_value string
	err := row.Scan(&encrypted_value)
	return encrypted_value, err
}

const getRawSecretByAlias = `-- name: GetRawSecretByAlias :one
SELECT id, COALESCE(encrypted_value, '')::text AS encrypted_value
FROM secret_references
WHERE alias = $1 AND is_active = TRUE
`

type GetRawSecretByAliasRow struct {
	ID             string `json:"id"`
	EncryptedValue string `json:"encrypted_value"`
}

func (q *Queries) GetRawSecretByAlias(ctx context.Context, alias string) (GetRawSecretByAliasRow, error) {
	row := q.db.QueryRow(ctx, getRawSecretByAlias, alias)
	var i GetRawSecretByAliasRow
	err := row.Scan(&i.ID, &i.EncryptedValue)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT
  id,
  name,
  alias,
  provider,
  COALESCE(description, '')::text AS description,
  COALESCE(secret_path, '')::text AS secret_path,
  COALESCE(secret_key, '')::text AS secret_key,
  is_active,
  created_at
FROM secret_references
WHERE id = $1
`

type GetSecretRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Alias       string           `json:"alias"`
	Provider    string           `json:"provider"`
	Description string           `json:"description"`
	SecretPath  string           `json:"secret_path"`
	SecretKey   string           `json:"secret_key"`
	IsActive    pgtype.Bool      `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetSecret(ctx context.Context, id string) (GetSecretRow, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i GetSecretRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Alias,
		&i.Provider,
		&i.Description,
		&i.SecretPath,
		&i.SecretKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listLegacySecretsForBackfill = `-- name: ListLegacySecretsForBackfill :many
SELECT id, alias
FROM secret_references
WHERE COALESCE(encrypted_value, '') = '' OR encrypted_value = 'encrypted-placeholder'
`

type ListLegacySecretsForBackfillRow struct {
	ID    string `json:"id"`
	Alias string `json:"alias"`
}

func (q *Queries) ListLegacySecretsForBackfill(ctx context.Context) ([]ListLegacySecretsForBackfillRow, error) {
	rows, err := q.db.Query(ctx, listLegacySecretsForBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegacySecretsForBackfillRow{}
	for rows.Next() {
		var i ListLegacySecretsForBackfillRow
		if err := rows.Scan(&i.ID, &i.Alias); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT
  id,
  name,
  alias,
  provider,
  COALESCE(description, '')::text AS description,
  COALESCE(secret_path, '')::text AS secret_path,
  COALESCE(secret_key, '')::text AS secret_key,
  is_active,
  created_at
FROM secret_references
ORDER BY created_at DESC
`

type ListSecretsRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Alias       string           `json:"alias"`
	Provider    string           `json:"provider"`
	Description string           `json:"description"`
	SecretPath  string           `json:"secret_path"`
	SecretKey   string           `json:"secret_key"`
	IsActive    pgtype.Bool      `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListSecrets(ctx context.Context) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Alias,
			&i.Provider,
			&i.Description,
			&i.SecretPath,
			&i.SecretKey,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecretEncryptedValue = `-- name: UpdateSecretEncryptedValue :exec
UPDATE secret_references
SET encrypted_value = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateSecretEncryptedValueParams struct {
	ID             string      `json:"id"`
	EncryptedValue pgtype.Text `json:"encrypted_value"`
}

func (q *Queries) UpdateSecretEncryptedValue(ctx context.Context, arg UpdateSecretEncryptedValueParams) error {
	_, err := q.db.Exec(ctx, updateSecretEncryptedValue, arg.ID, arg.EncryptedValue)
	return err
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO secret_references (
  id,
  name,
  alias,
  description,
  provider,
  secret_path,
  secret_key,
  encrypted_value,
  is_active,
  updated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $8,
  $9,
  $6,
  $7,
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  alias = EXCLUDED.alias,
  description = EXCLUDED.description,
  provider = EXCLUDED.provider,
  secret_path = EXCLUDED.secret_path,
  secret_key = EXCLUDED.secret_key,
  encrypted_value = EXCLUDED.encrypted_value,
  is_active = EXCLUDED.is_active,
  updated_at = NOW()
`

type UpsertSecretParams struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	Alias          string      `json:"alias"`
	Description    pgtype.Text `json:"description"`
	Provider       string      `json:"provider"`
	EncryptedValue pgtype.Text `json:"encrypted_value"`
	IsActive       pgtype.Bool `json:"is_active"`
	SecretPath     pgtype.Text `json:"secret_path"`
	SecretKey      pgtype.Text `json:"secret_key"`
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.Exec(ctx, upsertSecret,
		arg.ID,
		arg.Name,
		arg.Alias,
		arg.Description,
		arg.Provider,
		arg.EncryptedValue,
		arg.IsActive,
		arg.SecretPath,
		arg.SecretKey,
	)
	return err
}
