// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT value_json, updated_at
FROM system_settings
WHERE key = $1
`

type GetSystemSettingRow struct {
	ValueJson []byte           `json:"value_json"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (GetSystemSettingRow, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i GetSystemSettingRow
	err := row.Scan(&i.ValueJson, &i.UpdatedAt)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value_json, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET
  value_json = EXCLUDED.value_json,
  updated_at = NOW()
`

type UpsertSystemSettingParams struct {
	Key       string `json:"key"`
	ValueJson []byte `json:"value_json"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSystemSetting, arg.Key, arg.ValueJson)
	return err
}
